/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_Address_H_
#define	_Address_H_


#include <asn_application.h>

/* Including external dependencies */
#include "FEFString.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Address */
typedef FEFString_t	 Address_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Address;
asn_struct_free_f Address_free;
asn_struct_print_f Address_print;
asn_constr_check_f Address_constraint;
ber_type_decoder_f Address_decode_ber;
der_type_encoder_f Address_encode_der;
xer_type_decoder_f Address_decode_xer;
xer_type_encoder_f Address_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Address_H_ */
