/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#include <asn_internal.h>

#include "AlertCondition.h"

static asn_TYPE_member_t asn_MBR_AlertCondition_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AlertCondition, objreference),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HandleRef,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"objreference"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AlertCondition, controls),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AlertControls,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"controls"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AlertCondition, alertflags),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AlertFlags,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"alertflags"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AlertCondition, alertsource),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MetricsCode,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"alertsource"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AlertCondition, alertcode),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AlertCode,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"alertcode"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AlertCondition, alerttype),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AlertType,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"alerttype"
		},
	{ ATF_POINTER, 1, offsetof(struct AlertCondition, alertinfoid),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PrivateCode,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"alertinfoid"
		},
};
static ber_tlv_tag_t asn_DEF_AlertCondition_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_AlertCondition_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* objreference at 1401 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* controls at 1402 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 }, /* alertflags at 1403 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 3, 0, 0 }, /* alertsource at 1404 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 4, 0, 0 }, /* alertcode at 1405 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 5, 0, 0 }, /* alerttype at 1406 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 6, 0, 0 } /* alertinfoid at 1407 */
};
static asn_SEQUENCE_specifics_t asn_SPC_AlertCondition_specs_1 = {
	sizeof(struct AlertCondition),
	offsetof(struct AlertCondition, _asn_ctx),
	asn_MAP_AlertCondition_tag2el_1,
	7,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_AlertCondition = {
	"AlertCondition",
	"AlertCondition",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_AlertCondition_tags_1,
	sizeof(asn_DEF_AlertCondition_tags_1)
		/sizeof(asn_DEF_AlertCondition_tags_1[0]), /* 1 */
	asn_DEF_AlertCondition_tags_1,	/* Same as above */
	sizeof(asn_DEF_AlertCondition_tags_1)
		/sizeof(asn_DEF_AlertCondition_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_AlertCondition_1,
	7,	/* Elements count */
	&asn_SPC_AlertCondition_specs_1	/* Additional specs */
};

