/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_AlertCode_H_
#define	_AlertCode_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AlertCode */
typedef INTEGER_t	 AlertCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AlertCode;
asn_struct_free_f AlertCode_free;
asn_struct_print_f AlertCode_print;
asn_constr_check_f AlertCode_constraint;
ber_type_decoder_f AlertCode_decode_ber;
der_type_encoder_f AlertCode_encode_der;
xer_type_decoder_f AlertCode_decode_xer;
xer_type_encoder_f AlertCode_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _AlertCode_H_ */
