/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_AlertFlags_H_
#define	_AlertFlags_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AlertFlags {
	AlertFlags_localaudible	= 1,
	AlertFlags_remoteaudible	= 2,
	AlertFlags_visuallatching	= 3,
	AlertFlags_audiblelatching	= 4,
	AlertFlags_derived	= 6,
	AlertFlags_recordinhibit	= 8
} e_AlertFlags;

/* AlertFlags */
typedef BIT_STRING_t	 AlertFlags_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AlertFlags;
asn_struct_free_f AlertFlags_free;
asn_struct_print_f AlertFlags_print;
asn_constr_check_f AlertFlags_constraint;
ber_type_decoder_f AlertFlags_decode_ber;
der_type_encoder_f AlertFlags_encode_der;
xer_type_decoder_f AlertFlags_decode_xer;
xer_type_encoder_f AlertFlags_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _AlertFlags_H_ */
