/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_AlertSection_H_
#define	_AlertSection_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Handle.h"
#include "AlertCode.h"
#include "FEFString.h"
#include "ObservationTime.h"
#include "AlertCondition.h"
#include "HandleRef.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LimitSpecEntry;

/* AlertSection */
typedef struct AlertSection {
	Handle_t	 handle;
	AlertCode_t	 alerttype;
	FEFString_t	*labelstring	/* OPTIONAL */;
	ObservationTime_t	 timestamp;
	AlertCondition_t	 alertcondition;
	struct LimitSpecEntry	*limitspec	/* OPTIONAL */;
	HandleRef_t	*vmoreference	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AlertSection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AlertSection;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "LimitSpecEntry.h"

#endif	/* _AlertSection_H_ */
