/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_ArchiveProtection_H_
#define	_ArchiveProtection_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PrivateCode.h"
#include <ANY.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ArchiveProtection */
typedef struct ArchiveProtection {
	PrivateCode_t	 protectiontype;
	ANY_t	 protectionkey;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ArchiveProtection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ArchiveProtection;

#ifdef __cplusplus
}
#endif

#endif	/* _ArchiveProtection_H_ */
