/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_Authorization_H_
#define	_Authorization_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PrivateCode.h"
#include <ANY.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Authorization */
typedef struct Authorization {
	PrivateCode_t	 authorization_type;
	ANY_t	 authorization_key;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Authorization_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Authorization;

#ifdef __cplusplus
}
#endif

#endif	/* _Authorization_H_ */
