/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_ChannelDescriptionSection_H_
#define	_ChannelDescriptionSection_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Handle.h"
#include "MetricsCode.h"
#include "FEFString.h"
#include "MetricStatus.h"
#include "ParameterGroupCode.h"
#include <INTEGER.h>
#include "MsmtPrinciple.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ChannelDescriptionSection */
typedef struct ChannelDescriptionSection {
	Handle_t	 handle;
	MetricsCode_t	 metrictype;
	FEFString_t	*labelstring	/* OPTIONAL */;
	MetricsCode_t	*channelid	/* OPTIONAL */;
	MetricStatus_t	*channelstatus	/* DEFAULT {} */;
	ParameterGroupCode_t	*parametergroup	/* OPTIONAL */;
	INTEGER_t	*physicalchannelnr	/* DEFAULT 65535 */;
	MsmtPrinciple_t	*measurementprinciple	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ChannelDescriptionSection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ChannelDescriptionSection;

#ifdef __cplusplus
}
#endif

#endif	/* _ChannelDescriptionSection_H_ */
