/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_ChannelStatus_H_
#define	_ChannelStatus_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ChannelStatus {
	ChannelStatus_chn_off	= 0,
	ChannelStatus_chn_not_ready	= 1,
	ChannelStatus_chn_standby	= 2,
	ChannelStatus_chn_transduc_discon	= 8,
	ChannelStatus_chn_hw_discon	= 9
} e_ChannelStatus;

/* ChannelStatus */
typedef BIT_STRING_t	 ChannelStatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ChannelStatus;
asn_struct_free_f ChannelStatus_free;
asn_struct_print_f ChannelStatus_print;
asn_constr_check_f ChannelStatus_constraint;
ber_type_decoder_f ChannelStatus_decode_ber;
der_type_encoder_f ChannelStatus_encode_der;
xer_type_decoder_f ChannelStatus_decode_xer;
xer_type_encoder_f ChannelStatus_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ChannelStatus_H_ */
