/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_ChoiceOfEnumTimeStamp_H_
#define	_ChoiceOfEnumTimeStamp_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ObservationTime.h"
#include "AbsoluteTime.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include "RelativeTime.h"
#include "HighResRelativeTime.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ChoiceOfEnumTimeStamp_PR {
	ChoiceOfEnumTimeStamp_PR_NOTHING,	/* No components present */
	ChoiceOfEnumTimeStamp_PR_timestamp,
	ChoiceOfEnumTimeStamp_PR_absolutetimestamparray,
	ChoiceOfEnumTimeStamp_PR_relativetimestamparray,
	ChoiceOfEnumTimeStamp_PR_hirestimestamparray
} ChoiceOfEnumTimeStamp_PR;

/* ChoiceOfEnumTimeStamp */
typedef struct ChoiceOfEnumTimeStamp {
	ChoiceOfEnumTimeStamp_PR present;
	union ChoiceOfEnumTimeStamp_u {
		ObservationTime_t	 timestamp;
		struct ChoiceOfEnumTimeStamp__absolutetimestamparray {
			A_SEQUENCE_OF(AbsoluteTime_t) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} absolutetimestamparray;
		struct ChoiceOfEnumTimeStamp__relativetimestamparray {
			A_SEQUENCE_OF(RelativeTime_t) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} relativetimestamparray;
		struct ChoiceOfEnumTimeStamp__hirestimestamparray {
			A_SEQUENCE_OF(HighResRelativeTime_t) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} hirestimestamparray;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ChoiceOfEnumTimeStamp_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ChoiceOfEnumTimeStamp;

#ifdef __cplusplus
}
#endif

#endif	/* _ChoiceOfEnumTimeStamp_H_ */
