/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_ChoiceOfEnumObsValue_H_
#define	_ChoiceOfEnumObsValue_H_


#include <asn_application.h>

/* Including external dependencies */
#include "EnumObsValue.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ChoiceOfEnumObsValue_PR {
	ChoiceOfEnumObsValue_PR_NOTHING,	/* No components present */
	ChoiceOfEnumObsValue_PR_enumobservedvalue,
	ChoiceOfEnumObsValue_PR_compoundenumobservedvalue
} ChoiceOfEnumObsValue_PR;

/* Forward declarations */
struct EnumObsValue;

/* ChoiceOfEnumObsValue */
typedef struct ChoiceOfEnumObsValue {
	ChoiceOfEnumObsValue_PR present;
	union ChoiceOfEnumObsValue_u {
		EnumObsValue_t	 enumobservedvalue;
		struct ChoiceOfEnumObsValue__compoundenumobservedvalue {
			A_SEQUENCE_OF(struct EnumObsValue) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} compoundenumobservedvalue;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ChoiceOfEnumObsValue_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ChoiceOfEnumObsValue;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "EnumObsValue.h"

#endif	/* _ChoiceOfEnumObsValue_H_ */
