/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_ChoiceOfNuObsValue_H_
#define	_ChoiceOfNuObsValue_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NuObsValue.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ChoiceOfNuObsValue_PR {
	ChoiceOfNuObsValue_PR_NOTHING,	/* No components present */
	ChoiceOfNuObsValue_PR_nuobservedvalue,
	ChoiceOfNuObsValue_PR_compoundnuobservedvalue
} ChoiceOfNuObsValue_PR;

/* Forward declarations */
struct NuObsValue;

/* ChoiceOfNuObsValue */
typedef struct ChoiceOfNuObsValue {
	ChoiceOfNuObsValue_PR present;
	union ChoiceOfNuObsValue_u {
		NuObsValue_t	 nuobservedvalue;
		struct ChoiceOfNuObsValue__compoundnuobservedvalue {
			A_SEQUENCE_OF(struct NuObsValue) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} compoundnuobservedvalue;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ChoiceOfNuObsValue_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ChoiceOfNuObsValue;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "NuObsValue.h"

#endif	/* _ChoiceOfNuObsValue_H_ */
