/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#include <asn_internal.h>

#include "ChoiceOfNuObsValue.h"

static asn_TYPE_member_t asn_MBR_compoundnuobservedvalue_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_NuObsValue,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_compoundnuobservedvalue_tags_3[] = {
	(ASN_TAG_CLASS_APPLICATION | (2379 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_compoundnuobservedvalue_specs_3 = {
	sizeof(struct ChoiceOfNuObsValue__compoundnuobservedvalue),
	offsetof(struct ChoiceOfNuObsValue__compoundnuobservedvalue, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_compoundnuobservedvalue_3 = {
	"compoundnuobservedvalue",
	"compoundnuobservedvalue",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_compoundnuobservedvalue_tags_3,
	sizeof(asn_DEF_compoundnuobservedvalue_tags_3)
		/sizeof(asn_DEF_compoundnuobservedvalue_tags_3[0]) - 1, /* 1 */
	asn_DEF_compoundnuobservedvalue_tags_3,	/* Same as above */
	sizeof(asn_DEF_compoundnuobservedvalue_tags_3)
		/sizeof(asn_DEF_compoundnuobservedvalue_tags_3[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_compoundnuobservedvalue_3,
	1,	/* Single element */
	&asn_SPC_compoundnuobservedvalue_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ChoiceOfNuObsValue_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ChoiceOfNuObsValue, choice.nuobservedvalue),
		(ASN_TAG_CLASS_APPLICATION | (2384 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NuObsValue,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"nuobservedvalue"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ChoiceOfNuObsValue, choice.compoundnuobservedvalue),
		(ASN_TAG_CLASS_APPLICATION | (2379 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_compoundnuobservedvalue_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"compoundnuobservedvalue"
		},
};
static asn_TYPE_tag2member_t asn_MAP_ChoiceOfNuObsValue_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (2379 << 2)), 1, 0, 0 }, /* compoundnuobservedvalue at 1297 */
    { (ASN_TAG_CLASS_APPLICATION | (2384 << 2)), 0, 0, 0 } /* nuobservedvalue at 1289 */
};
static asn_CHOICE_specifics_t asn_SPC_ChoiceOfNuObsValue_specs_1 = {
	sizeof(struct ChoiceOfNuObsValue),
	offsetof(struct ChoiceOfNuObsValue, _asn_ctx),
	offsetof(struct ChoiceOfNuObsValue, present),
	sizeof(((struct ChoiceOfNuObsValue *)0)->present),
	asn_MAP_ChoiceOfNuObsValue_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ChoiceOfNuObsValue = {
	"ChoiceOfNuObsValue",
	"ChoiceOfNuObsValue",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_ChoiceOfNuObsValue_1,
	2,	/* Elements count */
	&asn_SPC_ChoiceOfNuObsValue_specs_1	/* Additional specs */
};

