/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#include <asn_internal.h>

#include "ChoiceOfEnumObsValue.h"

static asn_TYPE_member_t asn_MBR_compoundenumobservedvalue_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_EnumObsValue,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_compoundenumobservedvalue_tags_3[] = {
	(ASN_TAG_CLASS_APPLICATION | (2463 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_compoundenumobservedvalue_specs_3 = {
	sizeof(struct ChoiceOfEnumObsValue__compoundenumobservedvalue),
	offsetof(struct ChoiceOfEnumObsValue__compoundenumobservedvalue, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_compoundenumobservedvalue_3 = {
	"compoundenumobservedvalue",
	"compoundenumobservedvalue",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_compoundenumobservedvalue_tags_3,
	sizeof(asn_DEF_compoundenumobservedvalue_tags_3)
		/sizeof(asn_DEF_compoundenumobservedvalue_tags_3[0]) - 1, /* 1 */
	asn_DEF_compoundenumobservedvalue_tags_3,	/* Same as above */
	sizeof(asn_DEF_compoundenumobservedvalue_tags_3)
		/sizeof(asn_DEF_compoundenumobservedvalue_tags_3[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_compoundenumobservedvalue_3,
	1,	/* Single element */
	&asn_SPC_compoundenumobservedvalue_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ChoiceOfEnumObsValue_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ChoiceOfEnumObsValue, choice.enumobservedvalue),
		(ASN_TAG_CLASS_APPLICATION | (2462 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EnumObsValue,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"enumobservedvalue"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ChoiceOfEnumObsValue, choice.compoundenumobservedvalue),
		(ASN_TAG_CLASS_APPLICATION | (2463 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_compoundenumobservedvalue_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"compoundenumobservedvalue"
		},
};
static asn_TYPE_tag2member_t asn_MAP_ChoiceOfEnumObsValue_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (2462 << 2)), 0, 0, 0 }, /* enumobservedvalue at 1330 */
    { (ASN_TAG_CLASS_APPLICATION | (2463 << 2)), 1, 0, 0 } /* compoundenumobservedvalue at 1333 */
};
static asn_CHOICE_specifics_t asn_SPC_ChoiceOfEnumObsValue_specs_1 = {
	sizeof(struct ChoiceOfEnumObsValue),
	offsetof(struct ChoiceOfEnumObsValue, _asn_ctx),
	offsetof(struct ChoiceOfEnumObsValue, present),
	sizeof(((struct ChoiceOfEnumObsValue *)0)->present),
	asn_MAP_ChoiceOfEnumObsValue_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ChoiceOfEnumObsValue = {
	"ChoiceOfEnumObsValue",
	"ChoiceOfEnumObsValue",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_ChoiceOfEnumObsValue_1,
	2,	/* Elements count */
	&asn_SPC_ChoiceOfEnumObsValue_specs_1	/* Additional specs */
};

