/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_Comments_H_
#define	_Comments_H_


#include <asn_application.h>

/* Including external dependencies */
#include "FEFString.h"
#include "HandleRef.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Comments */
typedef struct Comments {
	FEFString_t	 commenttext;
	HandleRef_t	 commentator;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Comments_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Comments;

#ifdef __cplusplus
}
#endif

#endif	/* _Comments_H_ */
