/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_ContentOrReference_H_
#define	_ContentOrReference_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include "FEFString.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ContentOrReference_PR {
	ContentOrReference_PR_NOTHING,	/* No components present */
	ContentOrReference_PR_content,
	ContentOrReference_PR_reference
} ContentOrReference_PR;

/* ContentOrReference */
typedef struct ContentOrReference {
	ContentOrReference_PR present;
	union ContentOrReference_u {
		OCTET_STRING_t	 content;
		FEFString_t	 reference;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ContentOrReference_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ContentOrReference;

#ifdef __cplusplus
}
#endif

#endif	/* _ContentOrReference_H_ */
