/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_CurLimAlStat_H_
#define	_CurLimAlStat_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CurLimAlStat {
	CurLimAlStat_limalertoff	= 0,
	CurLimAlStat_limlowoff	= 1,
	CurLimAlStat_limhighoff	= 2
} e_CurLimAlStat;

/* CurLimAlStat */
typedef BIT_STRING_t	 CurLimAlStat_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CurLimAlStat;
asn_struct_free_f CurLimAlStat_free;
asn_struct_print_f CurLimAlStat_print;
asn_constr_check_f CurLimAlStat_constraint;
ber_type_decoder_f CurLimAlStat_decode_ber;
der_type_encoder_f CurLimAlStat_encode_der;
xer_type_decoder_f CurLimAlStat_decode_xer;
xer_type_encoder_f CurLimAlStat_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CurLimAlStat_H_ */
