/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_DistributionSampleArrayMeasuredDataSection_H_
#define	_DistributionSampleArrayMeasuredDataSection_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>
#include "Fraction.h"
#include "SampleArrayMeasuredDataBlock.h"
#include "HandleRef.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DistributionSampleArrayMeasuredDataSection */
typedef struct DistributionSampleArrayMeasuredDataSection {
	INTEGER_t	 numberofsubblocks;
	Fraction_t	 subblocklength;
	INTEGER_t	 subblocksize;
	struct DistributionSampleArrayMeasuredDataSection__metriclist {
		A_SEQUENCE_OF(HandleRef_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} metriclist;
	SampleArrayMeasuredDataBlock_t	 data;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DistributionSampleArrayMeasuredDataSection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DistributionSampleArrayMeasuredDataSection;

#ifdef __cplusplus
}
#endif

#endif	/* _DistributionSampleArrayMeasuredDataSection_H_ */
