/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#include <asn_internal.h>

#include "DistributionSampleArrayMeasuredDataSection.h"

static asn_TYPE_member_t asn_MBR_metriclist_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_HandleRef,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_metriclist_tags_5[] = {
	(ASN_TAG_CLASS_APPLICATION | (6038 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_metriclist_specs_5 = {
	sizeof(struct DistributionSampleArrayMeasuredDataSection__metriclist),
	offsetof(struct DistributionSampleArrayMeasuredDataSection__metriclist, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_metriclist_5 = {
	"metriclist",
	"metriclist",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_metriclist_tags_5,
	sizeof(asn_DEF_metriclist_tags_5)
		/sizeof(asn_DEF_metriclist_tags_5[0]) - 1, /* 1 */
	asn_DEF_metriclist_tags_5,	/* Same as above */
	sizeof(asn_DEF_metriclist_tags_5)
		/sizeof(asn_DEF_metriclist_tags_5[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_metriclist_5,
	1,	/* Single element */
	&asn_SPC_metriclist_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_DistributionSampleArrayMeasuredDataSection_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DistributionSampleArrayMeasuredDataSection, numberofsubblocks),
		(ASN_TAG_CLASS_APPLICATION | (6035 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"numberofsubblocks"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DistributionSampleArrayMeasuredDataSection, subblocklength),
		(ASN_TAG_CLASS_APPLICATION | (6036 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Fraction,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"subblocklength"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DistributionSampleArrayMeasuredDataSection, subblocksize),
		(ASN_TAG_CLASS_APPLICATION | (6037 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"subblocksize"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DistributionSampleArrayMeasuredDataSection, metriclist),
		(ASN_TAG_CLASS_APPLICATION | (6038 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_metriclist_5,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"metriclist"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DistributionSampleArrayMeasuredDataSection, data),
		(ASN_TAG_CLASS_APPLICATION | (6039 << 2)),
		0,
		&asn_DEF_SampleArrayMeasuredDataBlock,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"data"
		},
};
static ber_tlv_tag_t asn_DEF_DistributionSampleArrayMeasuredDataSection_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_DistributionSampleArrayMeasuredDataSection_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (6035 << 2)), 0, 0, 0 }, /* numberofsubblocks at 1220 */
    { (ASN_TAG_CLASS_APPLICATION | (6036 << 2)), 1, 0, 0 }, /* subblocklength at 1222 */
    { (ASN_TAG_CLASS_APPLICATION | (6037 << 2)), 2, 0, 0 }, /* subblocksize at 1225 */
    { (ASN_TAG_CLASS_APPLICATION | (6038 << 2)), 3, 0, 0 }, /* metriclist at 1230 */
    { (ASN_TAG_CLASS_APPLICATION | (6039 << 2)), 4, 0, 0 } /* data at 1275 */
};
static asn_SEQUENCE_specifics_t asn_SPC_DistributionSampleArrayMeasuredDataSection_specs_1 = {
	sizeof(struct DistributionSampleArrayMeasuredDataSection),
	offsetof(struct DistributionSampleArrayMeasuredDataSection, _asn_ctx),
	asn_MAP_DistributionSampleArrayMeasuredDataSection_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_DistributionSampleArrayMeasuredDataSection = {
	"DistributionSampleArrayMeasuredDataSection",
	"DistributionSampleArrayMeasuredDataSection",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_DistributionSampleArrayMeasuredDataSection_tags_1,
	sizeof(asn_DEF_DistributionSampleArrayMeasuredDataSection_tags_1)
		/sizeof(asn_DEF_DistributionSampleArrayMeasuredDataSection_tags_1[0]), /* 1 */
	asn_DEF_DistributionSampleArrayMeasuredDataSection_tags_1,	/* Same as above */
	sizeof(asn_DEF_DistributionSampleArrayMeasuredDataSection_tags_1)
		/sizeof(asn_DEF_DistributionSampleArrayMeasuredDataSection_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_DistributionSampleArrayMeasuredDataSection_1,
	5,	/* Elements count */
	&asn_SPC_DistributionSampleArrayMeasuredDataSection_specs_1	/* Additional specs */
};

