/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_DynamicAttributeChangeSection_H_
#define	_DynamicAttributeChangeSection_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ObservationTime.h"
#include "HandleRef.h"
#include <INTEGER.h>
#include <ANY.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DynamicAttributeChangeSection */
typedef struct DynamicAttributeChangeSection {
	ObservationTime_t	 timestamp;
	HandleRef_t	 handle;
	INTEGER_t	 attribute;
	ANY_t	*value	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DynamicAttributeChangeSection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DynamicAttributeChangeSection;

#ifdef __cplusplus
}
#endif

#endif	/* _DynamicAttributeChangeSection_H_ */
