/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_EnumerationMeasuredDataSection_H_
#define	_EnumerationMeasuredDataSection_H_


#include <asn_application.h>

/* Including external dependencies */
#include "HandleRef.h"
#include "ChoiceOfEnumObsValue.h"
#include "ChoiceOfEnumTimeStamp.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EnumerationMeasuredDataSection */
typedef struct EnumerationMeasuredDataSection {
	HandleRef_t	 metricref;
	ChoiceOfEnumObsValue_t	 enumobservedvalue;
	ChoiceOfEnumTimeStamp_t	 enumtimestamp;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EnumerationMeasuredDataSection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EnumerationMeasuredDataSection;

#ifdef __cplusplus
}
#endif

#endif	/* _EnumerationMeasuredDataSection_H_ */
