/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_EnumVal_H_
#define	_EnumVal_H_


#include <asn_application.h>

/* Including external dependencies */
#include "EnumObject.h"
#include "FEFString.h"
#include "ExtNomenRef.h"
#include <BIT_STRING.h>
#include "EnumRecordMetric.h"
#include "EnumRecordOO.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EnumVal_PR {
	EnumVal_PR_NOTHING,	/* No components present */
	EnumVal_PR_enum_obj_id,
	EnumVal_PR_enum_text_string,
	EnumVal_PR_enum_external_code,
	EnumVal_PR_enum_bit_str,
	EnumVal_PR_enum_record,
	EnumVal_PR_enum_record_oo
} EnumVal_PR;

/* EnumVal */
typedef struct EnumVal {
	EnumVal_PR present;
	union EnumVal_u {
		EnumObject_t	 enum_obj_id;
		FEFString_t	 enum_text_string;
		ExtNomenRef_t	 enum_external_code;
		BIT_STRING_t	 enum_bit_str;
		EnumRecordMetric_t	 enum_record;
		EnumRecordOO_t	 enum_record_oo;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EnumVal_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EnumVal;

#ifdef __cplusplus
}
#endif

#endif	/* _EnumVal_H_ */
