/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#include <asn_internal.h>

#include "EnumVal.h"

static asn_TYPE_member_t asn_MBR_EnumVal_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EnumVal, choice.enum_obj_id),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EnumObject,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"enum-obj-id"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EnumVal, choice.enum_text_string),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FEFString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"enum-text-string"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EnumVal, choice.enum_external_code),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ExtNomenRef,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"enum-external-code"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EnumVal, choice.enum_bit_str),
		(ASN_TAG_CLASS_CONTEXT | (16 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"enum-bit-str"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EnumVal, choice.enum_record),
		(ASN_TAG_CLASS_CONTEXT | (33 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EnumRecordMetric,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"enum-record"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EnumVal, choice.enum_record_oo),
		(ASN_TAG_CLASS_CONTEXT | (34 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EnumRecordOO,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"enum-record-oo"
		},
};
static asn_TYPE_tag2member_t asn_MAP_EnumVal_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* enum-obj-id at 1340 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* enum-text-string at 1341 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 2, 0, 0 }, /* enum-external-code at 1342 */
    { (ASN_TAG_CLASS_CONTEXT | (16 << 2)), 3, 0, 0 }, /* enum-bit-str at 1343 */
    { (ASN_TAG_CLASS_CONTEXT | (33 << 2)), 4, 0, 0 }, /* enum-record at 1344 */
    { (ASN_TAG_CLASS_CONTEXT | (34 << 2)), 5, 0, 0 } /* enum-record-oo at 1346 */
};
static asn_CHOICE_specifics_t asn_SPC_EnumVal_specs_1 = {
	sizeof(struct EnumVal),
	offsetof(struct EnumVal, _asn_ctx),
	offsetof(struct EnumVal, present),
	sizeof(((struct EnumVal *)0)->present),
	asn_MAP_EnumVal_tag2el_1,
	6,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_EnumVal = {
	"EnumVal",
	"EnumVal",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_EnumVal_1,
	6,	/* Elements count */
	&asn_SPC_EnumVal_specs_1	/* Additional specs */
};

