/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_EnumRecordMetric_H_
#define	_EnumRecordMetric_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MetricsCode.h"
#include <ANY.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EnumRecordMetric */
typedef struct EnumRecordMetric {
	MetricsCode_t	 record_type_code;
	ANY_t	 record_data;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EnumRecordMetric_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EnumRecordMetric;

#ifdef __cplusplus
}
#endif

#endif	/* _EnumRecordMetric_H_ */
