/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#include <asn_internal.h>

#include "EnumObject.h"

static asn_TYPE_member_t asn_MBR_EnumObject_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EnumObject, enum_obj_id),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_MetricsCode,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"enum-obj-id"
		},
	{ ATF_POINTER, 1, offsetof(struct EnumObject, enumadditionaldata),
		(ASN_TAG_CLASS_APPLICATION | (2498 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ANY,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"enumadditionaldata"
		},
};
static ber_tlv_tag_t asn_DEF_EnumObject_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_EnumObject_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* enum-obj-id at 1350 */
    { (ASN_TAG_CLASS_APPLICATION | (2498 << 2)), 1, 0, 0 } /* enumadditionaldata at 1351 */
};
static asn_SEQUENCE_specifics_t asn_SPC_EnumObject_specs_1 = {
	sizeof(struct EnumObject),
	offsetof(struct EnumObject, _asn_ctx),
	asn_MAP_EnumObject_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_EnumObject = {
	"EnumObject",
	"EnumObject",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_EnumObject_tags_1,
	sizeof(asn_DEF_EnumObject_tags_1)
		/sizeof(asn_DEF_EnumObject_tags_1[0]), /* 1 */
	asn_DEF_EnumObject_tags_1,	/* Same as above */
	sizeof(asn_DEF_EnumObject_tags_1)
		/sizeof(asn_DEF_EnumObject_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_EnumObject_1,
	2,	/* Elements count */
	&asn_SPC_EnumObject_specs_1	/* Additional specs */
};

