/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_ExtNomenclatureCode_H_
#define	_ExtNomenclatureCode_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ExtNomenclatureCode */
typedef INTEGER_t	 ExtNomenclatureCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ExtNomenclatureCode;
asn_struct_free_f ExtNomenclatureCode_free;
asn_struct_print_f ExtNomenclatureCode_print;
asn_constr_check_f ExtNomenclatureCode_constraint;
ber_type_decoder_f ExtNomenclatureCode_decode_ber;
der_type_encoder_f ExtNomenclatureCode_encode_der;
xer_type_decoder_f ExtNomenclatureCode_decode_xer;
xer_type_encoder_f ExtNomenclatureCode_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ExtNomenclatureCode_H_ */
