/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_ExtNomenRef_H_
#define	_ExtNomenRef_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ExtNomenclatureCode.h"
#include <ANY.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ExtNomenRef */
typedef struct ExtNomenRef {
	ExtNomenclatureCode_t	 nomenclatureid;
	ANY_t	 nomenclaturecode;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ExtNomenRef_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ExtNomenRef;

#ifdef __cplusplus
}
#endif

#endif	/* _ExtNomenRef_H_ */
