/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_FEFFloat_H_
#define	_FEFFloat_H_


#include <asn_application.h>

/* Including external dependencies */
#include <REAL.h>

#ifdef __cplusplus
extern "C" {
#endif

/* FEFFloat */
typedef REAL_t	 FEFFloat_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FEFFloat;
asn_struct_free_f FEFFloat_free;
asn_struct_print_f FEFFloat_print;
asn_constr_check_f FEFFloat_constraint;
ber_type_decoder_f FEFFloat_decode_ber;
der_type_encoder_f FEFFloat_encode_der;
xer_type_decoder_f FEFFloat_decode_xer;
xer_type_encoder_f FEFFloat_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _FEFFloat_H_ */
