/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_FEFString_H_
#define	_FEFString_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTF8String.h>

#ifdef __cplusplus
extern "C" {
#endif

/* FEFString */
typedef UTF8String_t	 FEFString_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FEFString;
asn_struct_free_f FEFString_free;
asn_struct_print_f FEFString_print;
asn_constr_check_f FEFString_constraint;
ber_type_decoder_f FEFString_decode_ber;
der_type_encoder_f FEFString_encode_der;
xer_type_decoder_f FEFString_decode_xer;
xer_type_encoder_f FEFString_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _FEFString_H_ */
