/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_HandleRef_H_
#define	_HandleRef_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>

#ifdef __cplusplus
extern "C" {
#endif

/* HandleRef */
typedef INTEGER_t	 HandleRef_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HandleRef;
asn_struct_free_f HandleRef_free;
asn_struct_print_f HandleRef_print;
asn_constr_check_f HandleRef_constraint;
ber_type_decoder_f HandleRef_decode_ber;
der_type_encoder_f HandleRef_encode_der;
xer_type_decoder_f HandleRef_decode_xer;
xer_type_encoder_f HandleRef_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _HandleRef_H_ */
