/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_HealthCareProviderId_H_
#define	_HealthCareProviderId_H_


#include <asn_application.h>

/* Including external dependencies */
#include "INT-U16.h"

#ifdef __cplusplus
extern "C" {
#endif

/* HealthCareProviderId */
typedef INT_U16_t	 HealthCareProviderId_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HealthCareProviderId;
asn_struct_free_f HealthCareProviderId_free;
asn_struct_print_f HealthCareProviderId_print;
asn_constr_check_f HealthCareProviderId_constraint;
ber_type_decoder_f HealthCareProviderId_decode_ber;
der_type_encoder_f HealthCareProviderId_encode_der;
xer_type_decoder_f HealthCareProviderId_decode_xer;
xer_type_encoder_f HealthCareProviderId_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _HealthCareProviderId_H_ */
