/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#include <asn_internal.h>

#include "HealthCareProviderSection.h"

static asn_TYPE_member_t asn_MBR_healthcareprofessionals_6[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_HealthCareProfessionalSection,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_healthcareprofessionals_tags_6[] = {
	(ASN_TAG_CLASS_APPLICATION | (7008 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_healthcareprofessionals_specs_6 = {
	sizeof(struct HealthCareProviderSection__healthcareprofessionals),
	offsetof(struct HealthCareProviderSection__healthcareprofessionals, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_healthcareprofessionals_6 = {
	"healthcareprofessionals",
	"healthcareprofessionals",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_healthcareprofessionals_tags_6,
	sizeof(asn_DEF_healthcareprofessionals_tags_6)
		/sizeof(asn_DEF_healthcareprofessionals_tags_6[0]) - 1, /* 1 */
	asn_DEF_healthcareprofessionals_tags_6,	/* Same as above */
	sizeof(asn_DEF_healthcareprofessionals_tags_6)
		/sizeof(asn_DEF_healthcareprofessionals_tags_6[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_healthcareprofessionals_6,
	1,	/* Single element */
	&asn_SPC_healthcareprofessionals_specs_6	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_HealthCareProviderSection_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct HealthCareProviderSection, identification),
		(ASN_TAG_CLASS_APPLICATION | (6008 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HealthCareProviderId,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"identification"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct HealthCareProviderSection, name),
		(ASN_TAG_CLASS_APPLICATION | (6009 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FEFString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"name"
		},
	{ ATF_POINTER, 3, offsetof(struct HealthCareProviderSection, address),
		(ASN_TAG_CLASS_APPLICATION | (6010 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Address,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"address"
		},
	{ ATF_POINTER, 2, offsetof(struct HealthCareProviderSection, placeholder),
		(ASN_TAG_CLASS_APPLICATION | (6499 << 2)),
		0,
		&asn_DEF_Placeholder,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"placeholder"
		},
	{ ATF_POINTER, 1, offsetof(struct HealthCareProviderSection, healthcareprofessionals),
		(ASN_TAG_CLASS_APPLICATION | (7008 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_healthcareprofessionals_6,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"healthcareprofessionals"
		},
};
static ber_tlv_tag_t asn_DEF_HealthCareProviderSection_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_HealthCareProviderSection_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (6008 << 2)), 0, 0, 0 }, /* identification at 285 */
    { (ASN_TAG_CLASS_APPLICATION | (6009 << 2)), 1, 0, 0 }, /* name at 288 */
    { (ASN_TAG_CLASS_APPLICATION | (6010 << 2)), 2, 0, 0 }, /* address at 291 */
    { (ASN_TAG_CLASS_APPLICATION | (6499 << 2)), 3, 0, 0 }, /* placeholder at 294 */
    { (ASN_TAG_CLASS_APPLICATION | (7008 << 2)), 4, 0, 0 } /* healthcareprofessionals at 298 */
};
static asn_SEQUENCE_specifics_t asn_SPC_HealthCareProviderSection_specs_1 = {
	sizeof(struct HealthCareProviderSection),
	offsetof(struct HealthCareProviderSection, _asn_ctx),
	asn_MAP_HealthCareProviderSection_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_HealthCareProviderSection = {
	"HealthCareProviderSection",
	"HealthCareProviderSection",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_HealthCareProviderSection_tags_1,
	sizeof(asn_DEF_HealthCareProviderSection_tags_1)
		/sizeof(asn_DEF_HealthCareProviderSection_tags_1[0]), /* 1 */
	asn_DEF_HealthCareProviderSection_tags_1,	/* Same as above */
	sizeof(asn_DEF_HealthCareProviderSection_tags_1)
		/sizeof(asn_DEF_HealthCareProviderSection_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_HealthCareProviderSection_1,
	5,	/* Elements count */
	&asn_SPC_HealthCareProviderSection_specs_1	/* Additional specs */
};

