/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_HealthCareProviderSection_H_
#define	_HealthCareProviderSection_H_


#include <asn_application.h>

/* Including external dependencies */
#include "HealthCareProviderId.h"
#include "FEFString.h"
#include "Address.h"
#include "Placeholder.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct HealthCareProfessionalSection;

/* HealthCareProviderSection */
typedef struct HealthCareProviderSection {
	HealthCareProviderId_t	 identification;
	FEFString_t	 name;
	Address_t	*address	/* OPTIONAL */;
	Placeholder_t	*placeholder	/* OPTIONAL */;
	struct HealthCareProviderSection__healthcareprofessionals {
		A_SEQUENCE_OF(struct HealthCareProfessionalSection) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *healthcareprofessionals;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HealthCareProviderSection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HealthCareProviderSection;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "HealthCareProfessionalSection.h"

#endif	/* _HealthCareProviderSection_H_ */
