/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_HighResRelativeTime_H_
#define	_HighResRelativeTime_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>

#ifdef __cplusplus
extern "C" {
#endif

/* HighResRelativeTime */
typedef INTEGER_t	 HighResRelativeTime_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HighResRelativeTime;
asn_struct_free_f HighResRelativeTime_free;
asn_struct_print_f HighResRelativeTime_print;
asn_constr_check_f HighResRelativeTime_constraint;
ber_type_decoder_f HighResRelativeTime_decode_ber;
der_type_encoder_f HighResRelativeTime_encode_der;
xer_type_decoder_f HighResRelativeTime_decode_xer;
xer_type_encoder_f HighResRelativeTime_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _HighResRelativeTime_H_ */
