/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_INT_U16_H_
#define	_INT_U16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* INT-U16 */
typedef long	 INT_U16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_INT_U16;
asn_struct_free_f INT_U16_free;
asn_struct_print_f INT_U16_print;
asn_constr_check_f INT_U16_constraint;
ber_type_decoder_f INT_U16_decode_ber;
der_type_encoder_f INT_U16_encode_der;
xer_type_decoder_f INT_U16_decode_xer;
xer_type_encoder_f INT_U16_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _INT_U16_H_ */
