/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#include <asn_internal.h>

#include "LimitSpecEntry.h"

static asn_TYPE_member_t asn_MBR_LimitSpecEntry_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LimitSpecEntry, sectionhandle),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HandleRef,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"sectionhandle"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LimitSpecEntry, alsourceid),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MetricsCode,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"alsourceid"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LimitSpecEntry, unitcode),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UnitCode,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"unitcode"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LimitSpecEntry, limalstat),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CurLimAlStat,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"limalstat"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LimitSpecEntry, limalval),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AbsoluteRange,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"limalval"
		},
};
static ber_tlv_tag_t asn_DEF_LimitSpecEntry_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_LimitSpecEntry_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* sectionhandle at 1441 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* alsourceid at 1442 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 }, /* unitcode at 1443 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 3, 0, 0 }, /* limalstat at 1444 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 4, 0, 0 } /* limalval at 1446 */
};
static asn_SEQUENCE_specifics_t asn_SPC_LimitSpecEntry_specs_1 = {
	sizeof(struct LimitSpecEntry),
	offsetof(struct LimitSpecEntry, _asn_ctx),
	asn_MAP_LimitSpecEntry_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_LimitSpecEntry = {
	"LimitSpecEntry",
	"LimitSpecEntry",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_LimitSpecEntry_tags_1,
	sizeof(asn_DEF_LimitSpecEntry_tags_1)
		/sizeof(asn_DEF_LimitSpecEntry_tags_1[0]), /* 1 */
	asn_DEF_LimitSpecEntry_tags_1,	/* Same as above */
	sizeof(asn_DEF_LimitSpecEntry_tags_1)
		/sizeof(asn_DEF_LimitSpecEntry_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_LimitSpecEntry_1,
	5,	/* Elements count */
	&asn_SPC_LimitSpecEntry_specs_1	/* Additional specs */
};

