/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_ManufacturerSpecificSection_H_
#define	_ManufacturerSpecificSection_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ManufacturerID.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ManufacturerSpecificEncoded;
struct ManufacturerSpecificBinary;

/* ManufacturerSpecificSection */
typedef struct ManufacturerSpecificSection {
	ManufacturerID_t	 manufacturerid;
	struct ManufacturerSpecificSection__encodedentries {
		A_SEQUENCE_OF(struct ManufacturerSpecificEncoded) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *encodedentries;
	struct ManufacturerSpecificSection__binaryentries {
		A_SEQUENCE_OF(struct ManufacturerSpecificBinary) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *binaryentries;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ManufacturerSpecificSection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ManufacturerSpecificSection;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ManufacturerSpecificEncoded.h"
#include "ManufacturerSpecificBinary.h"

#endif	/* _ManufacturerSpecificSection_H_ */
