/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_ManufacturerID_H_
#define	_ManufacturerID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OBJECT_IDENTIFIER.h>
#include <OCTET_STRING.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ManufacturerID_PR {
	ManufacturerID_PR_NOTHING,	/* No components present */
	ManufacturerID_PR_oid,
	ManufacturerID_PR_uuid
} ManufacturerID_PR;

/* ManufacturerID */
typedef struct ManufacturerID {
	ManufacturerID_PR present;
	union ManufacturerID_u {
		OBJECT_IDENTIFIER_t	 oid;
		OCTET_STRING_t	 uuid;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ManufacturerID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ManufacturerID;

#ifdef __cplusplus
}
#endif

#endif	/* _ManufacturerID_H_ */
