/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_MarkerEntryRelTim_H_
#define	_MarkerEntryRelTim_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MetricsCode.h"
#include "RelativeTime.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MarkerEntryRelTim */
typedef struct MarkerEntryRelTim {
	MetricsCode_t	 markerid;
	RelativeTime_t	 marktime;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MarkerEntryRelTim_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MarkerEntryRelTim;

#ifdef __cplusplus
}
#endif

#endif	/* _MarkerEntryRelTim_H_ */
