/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_MeasuredDataSection_H_
#define	_MeasuredDataSection_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RealTimeSampleArrayMeasuredDataSection;
struct TimeSampleArrayMeasuredDataSection;
struct DistributionSampleArrayMeasuredDataSection;
struct NumericMeasuredDataSection;
struct EnumerationMeasuredDataSection;
struct AlertSection;
struct DynamicAttributeChangeSection;

/* MeasuredDataSection */
typedef struct MeasuredDataSection {
	struct MeasuredDataSection__realtimesas {
		A_SEQUENCE_OF(struct RealTimeSampleArrayMeasuredDataSection) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *realtimesas;
	struct MeasuredDataSection__timesas {
		A_SEQUENCE_OF(struct TimeSampleArrayMeasuredDataSection) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *timesas;
	struct MeasuredDataSection__distributionsas {
		A_SEQUENCE_OF(struct DistributionSampleArrayMeasuredDataSection) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *distributionsas;
	struct MeasuredDataSection__numerics {
		A_SEQUENCE_OF(struct NumericMeasuredDataSection) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *numerics;
	struct MeasuredDataSection__enumerations {
		A_SEQUENCE_OF(struct EnumerationMeasuredDataSection) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *enumerations;
	struct MeasuredDataSection__alerts {
		A_SEQUENCE_OF(struct AlertSection) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *alerts;
	struct MeasuredDataSection__attributechanges {
		A_SEQUENCE_OF(struct DynamicAttributeChangeSection) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *attributechanges;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasuredDataSection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MeasuredDataSection;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RealTimeSampleArrayMeasuredDataSection.h"
#include "TimeSampleArrayMeasuredDataSection.h"
#include "DistributionSampleArrayMeasuredDataSection.h"
#include "NumericMeasuredDataSection.h"
#include "EnumerationMeasuredDataSection.h"
#include "AlertSection.h"
#include "DynamicAttributeChangeSection.h"

#endif	/* _MeasuredDataSection_H_ */
