/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_MedicalDeviceComponents_H_
#define	_MedicalDeviceComponents_H_


#include <asn_application.h>

/* Including external dependencies */
#include "VirtualMedicalDeviceSection.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MedicalDeviceComponents_PR {
	MedicalDeviceComponents_PR_NOTHING,	/* No components present */
	MedicalDeviceComponents_PR_medicaldevice,
	MedicalDeviceComponents_PR_medicaldevices,
	MedicalDeviceComponents_PR_subsystems
} MedicalDeviceComponents_PR;

/* Forward declarations */
struct VirtualMedicalDeviceSection;
struct MedicalDeviceSystemSection;

/* MedicalDeviceComponents */
typedef struct MedicalDeviceComponents {
	MedicalDeviceComponents_PR present;
	union MedicalDeviceComponents_u {
		VirtualMedicalDeviceSection_t	 medicaldevice;
		struct MedicalDeviceComponents__medicaldevices {
			A_SEQUENCE_OF(struct VirtualMedicalDeviceSection) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} medicaldevices;
		struct MedicalDeviceComponents__subsystems {
			A_SEQUENCE_OF(struct MedicalDeviceSystemSection) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} subsystems;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MedicalDeviceComponents_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MedicalDeviceComponents;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "VirtualMedicalDeviceSection.h"
#include "MedicalDeviceSystemSection.h"

#endif	/* _MedicalDeviceComponents_H_ */
