/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_MetricStatus_H_
#define	_MetricStatus_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MetricStatus {
	MetricStatus_metric_off	= 0,
	MetricStatus_metric_not_ready	= 1,
	MetricStatus_metric_standby	= 2,
	MetricStatus_metric_transduc_discon	= 8,
	MetricStatus_metric_hw_discon	= 9
} e_MetricStatus;

/* MetricStatus */
typedef BIT_STRING_t	 MetricStatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MetricStatus;
asn_struct_free_f MetricStatus_free;
asn_struct_print_f MetricStatus_print;
asn_constr_check_f MetricStatus_constraint;
ber_type_decoder_f MetricStatus_decode_ber;
der_type_encoder_f MetricStatus_encode_der;
xer_type_decoder_f MetricStatus_decode_xer;
xer_type_encoder_f MetricStatus_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _MetricStatus_H_ */
