/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_MetricMeasure_H_
#define	_MetricMeasure_H_


#include <asn_application.h>

/* Including external dependencies */
#include "FEFFloat.h"
#include "UnitsOfMeasurementCode.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MetricMeasure */
typedef struct MetricMeasure {
	FEFFloat_t	 value;
	UnitsOfMeasurementCode_t	 m_unit;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MetricMeasure_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MetricMeasure;

#ifdef __cplusplus
}
#endif

#endif	/* _MetricMeasure_H_ */
