/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_MetricsCode_H_
#define	_MetricsCode_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MetricsCode */
typedef INTEGER_t	 MetricsCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MetricsCode;
asn_struct_free_f MetricsCode_free;
asn_struct_print_f MetricsCode_print;
asn_constr_check_f MetricsCode_constraint;
ber_type_decoder_f MetricsCode_decode_ber;
der_type_encoder_f MetricsCode_encode_der;
xer_type_decoder_f MetricsCode_decode_xer;
xer_type_encoder_f MetricsCode_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _MetricsCode_H_ */
