/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#include <asn_internal.h>

#include "MetricMeasure.h"

static asn_TYPE_member_t asn_MBR_MetricMeasure_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MetricMeasure, value),
		(ASN_TAG_CLASS_UNIVERSAL | (9 << 2)),
		0,
		&asn_DEF_FEFFloat,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"value"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MetricMeasure, m_unit),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_UnitsOfMeasurementCode,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"m-unit"
		},
};
static ber_tlv_tag_t asn_DEF_MetricMeasure_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_MetricMeasure_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, 0, 0 }, /* m-unit at 31 */
    { (ASN_TAG_CLASS_UNIVERSAL | (9 << 2)), 0, 0, 0 } /* value at 29 */
};
static asn_SEQUENCE_specifics_t asn_SPC_MetricMeasure_specs_1 = {
	sizeof(struct MetricMeasure),
	offsetof(struct MetricMeasure, _asn_ctx),
	asn_MAP_MetricMeasure_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_MetricMeasure = {
	"MetricMeasure",
	"MetricMeasure",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_MetricMeasure_tags_1,
	sizeof(asn_DEF_MetricMeasure_tags_1)
		/sizeof(asn_DEF_MetricMeasure_tags_1[0]), /* 1 */
	asn_DEF_MetricMeasure_tags_1,	/* Same as above */
	sizeof(asn_DEF_MetricMeasure_tags_1)
		/sizeof(asn_DEF_MetricMeasure_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_MetricMeasure_1,
	2,	/* Elements count */
	&asn_SPC_MetricMeasure_specs_1	/* Additional specs */
};

