/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_MetricCategory_H_
#define	_MetricCategory_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MetricCategory {
	MetricCategory_mcat_unspec	= 0,
	MetricCategory_auto_measurement	= 1,
	MetricCategory_manual_measurement	= 2,
	MetricCategory_auto_setting	= 3,
	MetricCategory_manual_setting	= 4,
	MetricCategory_auto_calculation	= 5,
	MetricCategory_manual_calculation	= 6
} e_MetricCategory;

/* MetricCategory */
typedef INTEGER_t	 MetricCategory_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MetricCategory;
asn_struct_free_f MetricCategory_free;
asn_struct_print_f MetricCategory_print;
asn_constr_check_f MetricCategory_constraint;
ber_type_decoder_f MetricCategory_decode_ber;
der_type_encoder_f MetricCategory_encode_der;
xer_type_decoder_f MetricCategory_decode_xer;
xer_type_encoder_f MetricCategory_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _MetricCategory_H_ */
