/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_MsmtPrinciple_H_
#define	_MsmtPrinciple_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MsmtPrinciple {
	MsmtPrinciple_msp_chemical	= 1,
	MsmtPrinciple_msp_electrical	= 2,
	MsmtPrinciple_msp_impedance	= 3,
	MsmtPrinciple_msp_nuclear	= 4,
	MsmtPrinciple_msp_optical	= 5,
	MsmtPrinciple_msp_thermal	= 6,
	MsmtPrinciple_msp_biological	= 7,
	MsmtPrinciple_msp_mechanical	= 8,
	MsmtPrinciple_msp_manual	= 15
} e_MsmtPrinciple;

/* MsmtPrinciple */
typedef BIT_STRING_t	 MsmtPrinciple_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MsmtPrinciple;
asn_struct_free_f MsmtPrinciple_free;
asn_struct_print_f MsmtPrinciple_print;
asn_constr_check_f MsmtPrinciple_constraint;
ber_type_decoder_f MsmtPrinciple_decode_ber;
der_type_encoder_f MsmtPrinciple_encode_der;
xer_type_decoder_f MsmtPrinciple_decode_xer;
xer_type_encoder_f MsmtPrinciple_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _MsmtPrinciple_H_ */
