/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_MultimediaSection_H_
#define	_MultimediaSection_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AbsoluteTime.h"
#include "FEFString.h"
#include "Placeholder.h"
#include "ContentOrReference.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Comments;

/* MultimediaSection */
typedef struct MultimediaSection {
	AbsoluteTime_t	 starttime;
	AbsoluteTime_t	 stoptime;
	FEFString_t	 mimetype;
	struct Comments	*comments	/* OPTIONAL */;
	FEFString_t	*originallocation	/* OPTIONAL */;
	Placeholder_t	*placeholder	/* OPTIONAL */;
	ContentOrReference_t	 contentorreference;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MultimediaSection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MultimediaSection;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Comments.h"

#endif	/* _MultimediaSection_H_ */
