/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#include <asn_internal.h>

#include "MultimediaSection.h"

static asn_TYPE_member_t asn_MBR_MultimediaSection_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MultimediaSection, starttime),
		(ASN_TAG_CLASS_APPLICATION | (2538 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AbsoluteTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"starttime"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MultimediaSection, stoptime),
		(ASN_TAG_CLASS_APPLICATION | (2539 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AbsoluteTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"stoptime"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MultimediaSection, mimetype),
		(ASN_TAG_CLASS_APPLICATION | (6017 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FEFString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"mimetype"
		},
	{ ATF_POINTER, 3, offsetof(struct MultimediaSection, comments),
		(ASN_TAG_CLASS_APPLICATION | (6018 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Comments,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"comments"
		},
	{ ATF_POINTER, 2, offsetof(struct MultimediaSection, originallocation),
		(ASN_TAG_CLASS_APPLICATION | (6019 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FEFString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"originallocation"
		},
	{ ATF_POINTER, 1, offsetof(struct MultimediaSection, placeholder),
		(ASN_TAG_CLASS_APPLICATION | (6499 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Placeholder,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"placeholder"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MultimediaSection, contentorreference),
		(ASN_TAG_CLASS_APPLICATION | (6020 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ContentOrReference,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"contentorreference"
		},
};
static ber_tlv_tag_t asn_DEF_MultimediaSection_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_MultimediaSection_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (2538 << 2)), 0, 0, 0 }, /* starttime at 703 */
    { (ASN_TAG_CLASS_APPLICATION | (2539 << 2)), 1, 0, 0 }, /* stoptime at 704 */
    { (ASN_TAG_CLASS_APPLICATION | (6017 << 2)), 2, 0, 0 }, /* mimetype at 705 */
    { (ASN_TAG_CLASS_APPLICATION | (6018 << 2)), 3, 0, 0 }, /* comments at 706 */
    { (ASN_TAG_CLASS_APPLICATION | (6019 << 2)), 4, 0, 0 }, /* originallocation at 707 */
    { (ASN_TAG_CLASS_APPLICATION | (6020 << 2)), 6, 0, 0 }, /* contentorreference at 710 */
    { (ASN_TAG_CLASS_APPLICATION | (6499 << 2)), 5, 0, 0 } /* placeholder at 708 */
};
static asn_SEQUENCE_specifics_t asn_SPC_MultimediaSection_specs_1 = {
	sizeof(struct MultimediaSection),
	offsetof(struct MultimediaSection, _asn_ctx),
	asn_MAP_MultimediaSection_tag2el_1,
	7,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_MultimediaSection = {
	"MultimediaSection",
	"MultimediaSection",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_MultimediaSection_tags_1,
	sizeof(asn_DEF_MultimediaSection_tags_1)
		/sizeof(asn_DEF_MultimediaSection_tags_1[0]), /* 1 */
	asn_DEF_MultimediaSection_tags_1,	/* Same as above */
	sizeof(asn_DEF_MultimediaSection_tags_1)
		/sizeof(asn_DEF_MultimediaSection_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_MultimediaSection_1,
	7,	/* Elements count */
	&asn_SPC_MultimediaSection_specs_1	/* Additional specs */
};

