/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#include <asn_internal.h>

#include "NumericMeasuredDataSection.h"

static asn_TYPE_member_t asn_MBR_NumericMeasuredDataSection_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct NumericMeasuredDataSection, metricref),
		(ASN_TAG_CLASS_APPLICATION | (6050 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HandleRef,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"metricref"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NumericMeasuredDataSection, nuobservedvalue),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_ChoiceOfNuObsValue,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"nuobservedvalue"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NumericMeasuredDataSection, timestamp),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ObservationTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"timestamp"
		},
};
static ber_tlv_tag_t asn_DEF_NumericMeasuredDataSection_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_NumericMeasuredDataSection_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, 0, 0 }, /* timestamp at 1286 */
    { (ASN_TAG_CLASS_APPLICATION | (2379 << 2)), 1, 0, 0 }, /* compoundnuobservedvalue at 1297 */
    { (ASN_TAG_CLASS_APPLICATION | (2384 << 2)), 1, 0, 0 }, /* nuobservedvalue at 1289 */
    { (ASN_TAG_CLASS_APPLICATION | (6050 << 2)), 0, 0, 0 } /* metricref at 1280 */
};
static asn_SEQUENCE_specifics_t asn_SPC_NumericMeasuredDataSection_specs_1 = {
	sizeof(struct NumericMeasuredDataSection),
	offsetof(struct NumericMeasuredDataSection, _asn_ctx),
	asn_MAP_NumericMeasuredDataSection_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_NumericMeasuredDataSection = {
	"NumericMeasuredDataSection",
	"NumericMeasuredDataSection",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_NumericMeasuredDataSection_tags_1,
	sizeof(asn_DEF_NumericMeasuredDataSection_tags_1)
		/sizeof(asn_DEF_NumericMeasuredDataSection_tags_1[0]), /* 1 */
	asn_DEF_NumericMeasuredDataSection_tags_1,	/* Same as above */
	sizeof(asn_DEF_NumericMeasuredDataSection_tags_1)
		/sizeof(asn_DEF_NumericMeasuredDataSection_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_NumericMeasuredDataSection_1,
	3,	/* Elements count */
	&asn_SPC_NumericMeasuredDataSection_specs_1	/* Additional specs */
};

