/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_NumericMeasuredDataSection_H_
#define	_NumericMeasuredDataSection_H_


#include <asn_application.h>

/* Including external dependencies */
#include "HandleRef.h"
#include "ChoiceOfNuObsValue.h"
#include "ObservationTime.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NumericMeasuredDataSection */
typedef struct NumericMeasuredDataSection {
	HandleRef_t	 metricref;
	ChoiceOfNuObsValue_t	 nuobservedvalue;
	ObservationTime_t	 timestamp;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NumericMeasuredDataSection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NumericMeasuredDataSection;

#ifdef __cplusplus
}
#endif

#endif	/* _NumericMeasuredDataSection_H_ */
