/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_NuObsValue_H_
#define	_NuObsValue_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MetricsCode.h"
#include "MeasurementStatus.h"
#include "UnitsOfMeasurementCode.h"
#include "FEFFloat.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NuObsValue */
typedef struct NuObsValue {
	MetricsCode_t	*metricid	/* OPTIONAL */;
	MeasurementStatus_t	*state	/* DEFAULT {} */;
	UnitsOfMeasurementCode_t	*unitcode	/* OPTIONAL */;
	FEFFloat_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NuObsValue_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NuObsValue;

#ifdef __cplusplus
}
#endif

#endif	/* _NuObsValue_H_ */
