/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#include <asn_internal.h>

#include "ObservationTime.h"

static asn_TYPE_member_t asn_MBR_ObservationTime_1[] = {
	{ ATF_POINTER, 3, offsetof(struct ObservationTime, absolutetimestamp),
		(ASN_TAG_CLASS_APPLICATION | (2448 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AbsoluteTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"absolutetimestamp"
		},
	{ ATF_POINTER, 2, offsetof(struct ObservationTime, relativetimestamp),
		(ASN_TAG_CLASS_APPLICATION | (2449 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RelativeTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"relativetimestamp"
		},
	{ ATF_POINTER, 1, offsetof(struct ObservationTime, hirestimerelativestamp),
		(ASN_TAG_CLASS_APPLICATION | (2537 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HighResRelativeTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"hirestimerelativestamp"
		},
};
static ber_tlv_tag_t asn_DEF_ObservationTime_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_ObservationTime_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (2448 << 2)), 0, 0, 0 }, /* absolutetimestamp at 158 */
    { (ASN_TAG_CLASS_APPLICATION | (2449 << 2)), 1, 0, 0 }, /* relativetimestamp at 159 */
    { (ASN_TAG_CLASS_APPLICATION | (2537 << 2)), 2, 0, 0 } /* hirestimerelativestamp at 160 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ObservationTime_specs_1 = {
	sizeof(struct ObservationTime),
	offsetof(struct ObservationTime, _asn_ctx),
	asn_MAP_ObservationTime_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ObservationTime = {
	"ObservationTime",
	"ObservationTime",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ObservationTime_tags_1,
	sizeof(asn_DEF_ObservationTime_tags_1)
		/sizeof(asn_DEF_ObservationTime_tags_1[0]), /* 1 */
	asn_DEF_ObservationTime_tags_1,	/* Same as above */
	sizeof(asn_DEF_ObservationTime_tags_1)
		/sizeof(asn_DEF_ObservationTime_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ObservationTime_1,
	3,	/* Elements count */
	&asn_SPC_ObservationTime_specs_1	/* Additional specs */
};

