/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_OID_Type_H_
#define	_OID_Type_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>

#ifdef __cplusplus
extern "C" {
#endif

/* OID-Type */
typedef INTEGER_t	 OID_Type_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OID_Type;
asn_struct_free_f OID_Type_free;
asn_struct_print_f OID_Type_print;
asn_constr_check_f OID_Type_constraint;
ber_type_decoder_f OID_Type_decode_ber;
der_type_encoder_f OID_Type_encode_der;
xer_type_decoder_f OID_Type_decode_xer;
xer_type_encoder_f OID_Type_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _OID_Type_H_ */
