/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_PatientSex_H_
#define	_PatientSex_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PatientSex {
	PatientSex_sex_unknown	= 0,
	PatientSex_male	= 1,
	PatientSex_female	= 2,
	PatientSex_sex_unspecified	= 9
} e_PatientSex;

/* PatientSex */
typedef INTEGER_t	 PatientSex_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PatientSex;
asn_struct_free_f PatientSex_free;
asn_struct_print_f PatientSex_print;
asn_constr_check_f PatientSex_constraint;
ber_type_decoder_f PatientSex_decode_ber;
der_type_encoder_f PatientSex_encode_der;
xer_type_decoder_f PatientSex_decode_xer;
xer_type_encoder_f PatientSex_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _PatientSex_H_ */
