/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_PatientRace_H_
#define	_PatientRace_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PatientRace {
	PatientRace_race_unspecified	= 0,
	PatientRace_race_caucasian	= 1,
	PatientRace_race_black	= 2,
	PatientRace_race_oriental	= 3
} e_PatientRace;

/* PatientRace */
typedef INTEGER_t	 PatientRace_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PatientRace;
asn_struct_free_f PatientRace_free;
asn_struct_print_f PatientRace_print;
asn_constr_check_f PatientRace_constraint;
ber_type_decoder_f PatientRace_decode_ber;
der_type_encoder_f PatientRace_encode_der;
xer_type_decoder_f PatientRace_decode_xer;
xer_type_encoder_f PatientRace_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _PatientRace_H_ */
