/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_PersonName_H_
#define	_PersonName_H_


#include <asn_application.h>

/* Including external dependencies */
#include "FEFString.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PersonNameGroup;

/* PersonName */
typedef struct PersonName {
	FEFString_t	*ungroupedname	/* OPTIONAL */;
	struct PersonNameGroup	*characternamegroup	/* OPTIONAL */;
	struct PersonNameGroup	*ideographicnamegroup	/* OPTIONAL */;
	struct PersonNameGroup	*phoneticnamegroup	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PersonName_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PersonName;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PersonNameGroup.h"

#endif	/* _PersonName_H_ */
