/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#include <asn_internal.h>

#include "PersonNameGroup.h"

static asn_TYPE_member_t asn_MBR_PersonNameGroup_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PersonNameGroup, familyname),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FEFString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"familyname"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PersonNameGroup, givenname),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FEFString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"givenname"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PersonNameGroup, middlename),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FEFString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"middlename"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PersonNameGroup, prefix),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FEFString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"prefix"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PersonNameGroup, suffix),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FEFString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"suffix"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PersonNameGroup, degree),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FEFString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"degree"
		},
};
static ber_tlv_tag_t asn_DEF_PersonNameGroup_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_PersonNameGroup_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* familyname at 186 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* givenname at 187 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 }, /* middlename at 188 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 3, 0, 0 }, /* prefix at 189 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 4, 0, 0 }, /* suffix at 190 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 5, 0, 0 } /* degree at 192 */
};
static asn_SEQUENCE_specifics_t asn_SPC_PersonNameGroup_specs_1 = {
	sizeof(struct PersonNameGroup),
	offsetof(struct PersonNameGroup, _asn_ctx),
	asn_MAP_PersonNameGroup_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_PersonNameGroup = {
	"PersonNameGroup",
	"PersonNameGroup",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_PersonNameGroup_tags_1,
	sizeof(asn_DEF_PersonNameGroup_tags_1)
		/sizeof(asn_DEF_PersonNameGroup_tags_1[0]), /* 1 */
	asn_DEF_PersonNameGroup_tags_1,	/* Same as above */
	sizeof(asn_DEF_PersonNameGroup_tags_1)
		/sizeof(asn_DEF_PersonNameGroup_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_PersonNameGroup_1,
	6,	/* Elements count */
	&asn_SPC_PersonNameGroup_specs_1	/* Additional specs */
};

