/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_Placeholder_H_
#define	_Placeholder_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Placeholder */
typedef OCTET_STRING_t	 Placeholder_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Placeholder;
asn_struct_free_f Placeholder_free;
asn_struct_print_f Placeholder_print;
asn_constr_check_f Placeholder_constraint;
ber_type_decoder_f Placeholder_decode_ber;
der_type_encoder_f Placeholder_encode_der;
xer_type_decoder_f Placeholder_decode_xer;
xer_type_encoder_f Placeholder_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Placeholder_H_ */
