/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_PowerStatus_H_
#define	_PowerStatus_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PowerStatus {
	PowerStatus_onMains	= 0,
	PowerStatus_onBattery	= 1,
	PowerStatus_chargingFull	= 8,
	PowerStatus_chargingTrickle	= 9,
	PowerStatus_chargingOff	= 10
} e_PowerStatus;

/* PowerStatus */
typedef BIT_STRING_t	 PowerStatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PowerStatus;
asn_struct_free_f PowerStatus_free;
asn_struct_print_f PowerStatus_print;
asn_constr_check_f PowerStatus_constraint;
ber_type_decoder_f PowerStatus_decode_ber;
der_type_encoder_f PowerStatus_encode_der;
xer_type_decoder_f PowerStatus_decode_xer;
xer_type_encoder_f PowerStatus_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _PowerStatus_H_ */
