/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_SaCalData_H_
#define	_SaCalData_H_


#include <asn_application.h>

/* Including external dependencies */
#include "FEFFloat.h"
#include "SaCalDataType.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SaCalData */
typedef struct SaCalData {
	FEFFloat_t	 lowerabsolutevalue;
	FEFFloat_t	 upperabsolutevalue;
	FEFFloat_t	 increment;
	SaCalDataType_t	 cal_type;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SaCalData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SaCalData;

#ifdef __cplusplus
}
#endif

#endif	/* _SaCalData_H_ */
