/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_SaCalDataType_H_
#define	_SaCalDataType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SaCalDataType {
	SaCalDataType_bar	= 0,
	SaCalDataType_stair	= 1
} e_SaCalDataType;

/* SaCalDataType */
typedef INTEGER_t	 SaCalDataType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SaCalDataType;
asn_struct_free_f SaCalDataType_free;
asn_struct_print_f SaCalDataType_print;
asn_constr_check_f SaCalDataType_constraint;
ber_type_decoder_f SaCalDataType_decode_ber;
der_type_encoder_f SaCalDataType_encode_der;
xer_type_decoder_f SaCalDataType_decode_xer;
xer_type_encoder_f SaCalDataType_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SaCalDataType_H_ */
