/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#include <asn_internal.h>

#include "SaCalData.h"

static asn_TYPE_member_t asn_MBR_SaCalData_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SaCalData, lowerabsolutevalue),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FEFFloat,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"lowerabsolutevalue"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SaCalData, upperabsolutevalue),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FEFFloat,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"upperabsolutevalue"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SaCalData, increment),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FEFFloat,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"increment"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SaCalData, cal_type),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SaCalDataType,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"cal-type"
		},
};
static ber_tlv_tag_t asn_DEF_SaCalData_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_SaCalData_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* lowerabsolutevalue at 1065 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* upperabsolutevalue at 1066 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 2, 0, 0 }, /* increment at 1067 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 3, 0, 0 } /* cal-type at 1070 */
};
static asn_SEQUENCE_specifics_t asn_SPC_SaCalData_specs_1 = {
	sizeof(struct SaCalData),
	offsetof(struct SaCalData, _asn_ctx),
	asn_MAP_SaCalData_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SaCalData = {
	"SaCalData",
	"SaCalData",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SaCalData_tags_1,
	sizeof(asn_DEF_SaCalData_tags_1)
		/sizeof(asn_DEF_SaCalData_tags_1[0]), /* 1 */
	asn_DEF_SaCalData_tags_1,	/* Same as above */
	sizeof(asn_DEF_SaCalData_tags_1)
		/sizeof(asn_DEF_SaCalData_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SaCalData_1,
	4,	/* Elements count */
	&asn_SPC_SaCalData_specs_1	/* Additional specs */
};

