/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_SaFlags_H_
#define	_SaFlags_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SaFlags {
	SaFlags_smoothcurve	= 0,
	SaFlags_delayedcurve	= 1,
	SaFlags_saextvalrange	= 3
} e_SaFlags;

/* SaFlags */
typedef BIT_STRING_t	 SaFlags_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SaFlags;
asn_struct_free_f SaFlags_free;
asn_struct_print_f SaFlags_print;
asn_constr_check_f SaFlags_constraint;
ber_type_decoder_f SaFlags_decode_ber;
der_type_encoder_f SaFlags_encode_der;
xer_type_decoder_f SaFlags_decode_xer;
xer_type_encoder_f SaFlags_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SaFlags_H_ */
