/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_SaGridEntry_H_
#define	_SaGridEntry_H_


#include <asn_application.h>

/* Including external dependencies */
#include "FEFFloat.h"
#include <INTEGER.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SaGridEntry */
typedef struct SaGridEntry {
	FEFFloat_t	 absolute_value;
	INTEGER_t	 level;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SaGridEntry_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SaGridEntry;

#ifdef __cplusplus
}
#endif

#endif	/* _SaGridEntry_H_ */
