/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#include <asn_internal.h>

#include "SaSpec.h"

static asn_TYPE_member_t asn_MBR_SaSpec_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SaSpec, storagesize),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"storagesize"
		},
	{ ATF_POINTER, 1, offsetof(struct SaSpec, significantbits),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"significantbits"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SaSpec, storagedatatype),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_StorageDataType,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"storagedatatype"
		},
	{ ATF_POINTER, 1, offsetof(struct SaSpec, flags),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SaFlags,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"flags"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SaSpec, arraysize),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"arraysize"
		},
};
static ber_tlv_tag_t asn_DEF_SaSpec_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_SaSpec_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* storagesize at 994 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* significantbits at 997 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 }, /* storagedatatype at 1001 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 3, 0, 0 }, /* flags at 1002 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 4, 0, 0 } /* arraysize at 1005 */
};
static asn_SEQUENCE_specifics_t asn_SPC_SaSpec_specs_1 = {
	sizeof(struct SaSpec),
	offsetof(struct SaSpec, _asn_ctx),
	asn_MAP_SaSpec_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SaSpec = {
	"SaSpec",
	"SaSpec",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SaSpec_tags_1,
	sizeof(asn_DEF_SaSpec_tags_1)
		/sizeof(asn_DEF_SaSpec_tags_1[0]), /* 1 */
	asn_DEF_SaSpec_tags_1,	/* Same as above */
	sizeof(asn_DEF_SaSpec_tags_1)
		/sizeof(asn_DEF_SaSpec_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SaSpec_1,
	5,	/* Elements count */
	&asn_SPC_SaSpec_specs_1	/* Additional specs */
};

