/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_SaSpec_H_
#define	_SaSpec_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>
#include "StorageDataType.h"
#include "SaFlags.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SaSpec */
typedef struct SaSpec {
	INTEGER_t	 storagesize;
	INTEGER_t	*significantbits	/* OPTIONAL */;
	StorageDataType_t	 storagedatatype;
	SaFlags_t	*flags	/* DEFAULT {} */;
	INTEGER_t	 arraysize;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SaSpec_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SaSpec;

#ifdef __cplusplus
}
#endif

#endif	/* _SaSpec_H_ */
