/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_SessionNotesSection_H_
#define	_SessionNotesSection_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Handle.h"
#include "FEFString.h"
#include "AbsoluteTime.h"
#include "Placeholder.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ArchiveProtection;
struct ExtNomenRef;

/* SessionNotesSection */
typedef struct SessionNotesSection {
	Handle_t	 handle;
	FEFString_t	 sn_id;
	FEFString_t	 sn_name;
	FEFString_t	*sn_comments	/* OPTIONAL */;
	AbsoluteTime_t	 starttime;
	AbsoluteTime_t	 stoptime;
	FEFString_t	*findings	/* OPTIONAL */;
	struct SessionNotesSection__diagnosticscodes {
		A_SEQUENCE_OF(struct ExtNomenRef) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *diagnosticscodes;
	FEFString_t	*diagnosisdescription	/* OPTIONAL */;
	struct SessionNotesSection__procedurecodes {
		A_SEQUENCE_OF(struct ExtNomenRef) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *procedurecodes;
	FEFString_t	*proceduredescription	/* OPTIONAL */;
	struct ArchiveProtection	*protection	/* OPTIONAL */;
	Placeholder_t	*placeholder	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SessionNotesSection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SessionNotesSection;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ArchiveProtection.h"
#include "ExtNomenRef.h"

#endif	/* _SessionNotesSection_H_ */
