/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_SessionTestSection_H_
#define	_SessionTestSection_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Handle.h"
#include "FEFString.h"
#include "AbsoluteTime.h"
#include "Placeholder.h"
#include "MedicalDeviceSystemSection.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ArchiveProtection;
struct MultimediaSection;
struct SessionPhaseSection;

/* SessionTestSection */
typedef struct SessionTestSection {
	Handle_t	 handle;
	FEFString_t	 st_archive_id;
	FEFString_t	 st_archive_name;
	FEFString_t	*st_archive_comments	/* OPTIONAL */;
	AbsoluteTime_t	 starttime;
	AbsoluteTime_t	 stoptime;
	struct ArchiveProtection	*protection	/* OPTIONAL */;
	Placeholder_t	*placeholder	/* OPTIONAL */;
	MedicalDeviceSystemSection_t	 medicaldevicesystem;
	struct SessionTestSection__multimedia {
		A_SEQUENCE_OF(struct MultimediaSection) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *multimedia;
	struct SessionTestSection__phases {
		A_SEQUENCE_OF(struct SessionPhaseSection) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} phases;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SessionTestSection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SessionTestSection;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ArchiveProtection.h"
#include "MultimediaSection.h"
#include "SessionPhaseSection.h"

#endif	/* _SessionTestSection_H_ */
