/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#include <asn_internal.h>

#include "SessionTestSection.h"

static asn_TYPE_member_t asn_MBR_multimedia_11[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_MultimediaSection,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_multimedia_tags_11[] = {
	(ASN_TAG_CLASS_APPLICATION | (7006 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_multimedia_specs_11 = {
	sizeof(struct SessionTestSection__multimedia),
	offsetof(struct SessionTestSection__multimedia, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_multimedia_11 = {
	"multimedia",
	"multimedia",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_multimedia_tags_11,
	sizeof(asn_DEF_multimedia_tags_11)
		/sizeof(asn_DEF_multimedia_tags_11[0]) - 1, /* 1 */
	asn_DEF_multimedia_tags_11,	/* Same as above */
	sizeof(asn_DEF_multimedia_tags_11)
		/sizeof(asn_DEF_multimedia_tags_11[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_multimedia_11,
	1,	/* Single element */
	&asn_SPC_multimedia_specs_11	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_phases_13[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SessionPhaseSection,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_phases_tags_13[] = {
	(ASN_TAG_CLASS_APPLICATION | (7017 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_phases_specs_13 = {
	sizeof(struct SessionTestSection__phases),
	offsetof(struct SessionTestSection__phases, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_phases_13 = {
	"phases",
	"phases",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_phases_tags_13,
	sizeof(asn_DEF_phases_tags_13)
		/sizeof(asn_DEF_phases_tags_13[0]) - 1, /* 1 */
	asn_DEF_phases_tags_13,	/* Same as above */
	sizeof(asn_DEF_phases_tags_13)
		/sizeof(asn_DEF_phases_tags_13[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_phases_13,
	1,	/* Single element */
	&asn_SPC_phases_specs_13	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_SessionTestSection_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SessionTestSection, handle),
		(ASN_TAG_CLASS_APPLICATION | (2337 << 2)),
		0,
		&asn_DEF_Handle,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"handle"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SessionTestSection, st_archive_id),
		(ASN_TAG_CLASS_APPLICATION | (2506 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FEFString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"st-archive-id"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SessionTestSection, st_archive_name),
		(ASN_TAG_CLASS_APPLICATION | (2512 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FEFString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"st-archive-name"
		},
	{ ATF_POINTER, 1, offsetof(struct SessionTestSection, st_archive_comments),
		(ASN_TAG_CLASS_APPLICATION | (2529 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FEFString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"st-archive-comments"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SessionTestSection, starttime),
		(ASN_TAG_CLASS_APPLICATION | (2538 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AbsoluteTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"starttime"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SessionTestSection, stoptime),
		(ASN_TAG_CLASS_APPLICATION | (2539 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AbsoluteTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"stoptime"
		},
	{ ATF_POINTER, 2, offsetof(struct SessionTestSection, protection),
		(ASN_TAG_CLASS_APPLICATION | (2519 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ArchiveProtection,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"protection"
		},
	{ ATF_POINTER, 1, offsetof(struct SessionTestSection, placeholder),
		(ASN_TAG_CLASS_APPLICATION | (6499 << 2)),
		0,
		&asn_DEF_Placeholder,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"placeholder"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SessionTestSection, medicaldevicesystem),
		(ASN_TAG_CLASS_APPLICATION | (7005 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MedicalDeviceSystemSection,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"medicaldevicesystem"
		},
	{ ATF_POINTER, 1, offsetof(struct SessionTestSection, multimedia),
		(ASN_TAG_CLASS_APPLICATION | (7006 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_multimedia_11,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"multimedia"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SessionTestSection, phases),
		(ASN_TAG_CLASS_APPLICATION | (7017 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_phases_13,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"phases"
		},
};
static ber_tlv_tag_t asn_DEF_SessionTestSection_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_SessionTestSection_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (2337 << 2)), 0, 0, 0 }, /* handle at 453 */
    { (ASN_TAG_CLASS_APPLICATION | (2506 << 2)), 1, 0, 0 }, /* st-archive-id at 456 */
    { (ASN_TAG_CLASS_APPLICATION | (2512 << 2)), 2, 0, 0 }, /* st-archive-name at 458 */
    { (ASN_TAG_CLASS_APPLICATION | (2519 << 2)), 6, 0, 0 }, /* protection at 466 */
    { (ASN_TAG_CLASS_APPLICATION | (2529 << 2)), 3, 0, 0 }, /* st-archive-comments at 460 */
    { (ASN_TAG_CLASS_APPLICATION | (2538 << 2)), 4, 0, 0 }, /* starttime at 462 */
    { (ASN_TAG_CLASS_APPLICATION | (2539 << 2)), 5, 0, 0 }, /* stoptime at 464 */
    { (ASN_TAG_CLASS_APPLICATION | (6499 << 2)), 7, 0, 0 }, /* placeholder at 468 */
    { (ASN_TAG_CLASS_APPLICATION | (7005 << 2)), 8, 0, 0 }, /* medicaldevicesystem at 470 */
    { (ASN_TAG_CLASS_APPLICATION | (7006 << 2)), 9, 0, 0 }, /* multimedia at 473 */
    { (ASN_TAG_CLASS_APPLICATION | (7017 << 2)), 10, 0, 0 } /* phases at 478 */
};
static asn_SEQUENCE_specifics_t asn_SPC_SessionTestSection_specs_1 = {
	sizeof(struct SessionTestSection),
	offsetof(struct SessionTestSection, _asn_ctx),
	asn_MAP_SessionTestSection_tag2el_1,
	11,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SessionTestSection = {
	"SessionTestSection",
	"SessionTestSection",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SessionTestSection_tags_1,
	sizeof(asn_DEF_SessionTestSection_tags_1)
		/sizeof(asn_DEF_SessionTestSection_tags_1[0]), /* 1 */
	asn_DEF_SessionTestSection_tags_1,	/* Same as above */
	sizeof(asn_DEF_SessionTestSection_tags_1)
		/sizeof(asn_DEF_SessionTestSection_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SessionTestSection_1,
	11,	/* Elements count */
	&asn_SPC_SessionTestSection_specs_1	/* Additional specs */
};

