/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#include <asn_internal.h>

#include "SessionPhaseSection.h"

static asn_TYPE_member_t asn_MBR_measureddata_7[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_MeasuredDataSection,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_measureddata_tags_7[] = {
	(ASN_TAG_CLASS_APPLICATION | (7019 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_measureddata_specs_7 = {
	sizeof(struct SessionPhaseSection__measureddata),
	offsetof(struct SessionPhaseSection__measureddata, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_measureddata_7 = {
	"measureddata",
	"measureddata",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_measureddata_tags_7,
	sizeof(asn_DEF_measureddata_tags_7)
		/sizeof(asn_DEF_measureddata_tags_7[0]) - 1, /* 1 */
	asn_DEF_measureddata_tags_7,	/* Same as above */
	sizeof(asn_DEF_measureddata_tags_7)
		/sizeof(asn_DEF_measureddata_tags_7[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_measureddata_7,
	1,	/* Single element */
	&asn_SPC_measureddata_specs_7	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_SessionPhaseSection_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SessionPhaseSection, handle),
		(ASN_TAG_CLASS_APPLICATION | (2337 << 2)),
		0,
		&asn_DEF_Handle,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"handle"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SessionPhaseSection, starttime),
		(ASN_TAG_CLASS_APPLICATION | (2538 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AbsoluteTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"starttime"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SessionPhaseSection, stoptime),
		(ASN_TAG_CLASS_APPLICATION | (2539 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AbsoluteTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"stoptime"
		},
	{ ATF_POINTER, 1, offsetof(struct SessionPhaseSection, placeholder),
		(ASN_TAG_CLASS_APPLICATION | (6499 << 2)),
		0,
		&asn_DEF_Placeholder,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"placeholder"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SessionPhaseSection, descriptivedata),
		(ASN_TAG_CLASS_APPLICATION | (7018 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DescriptiveDataSection,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"descriptivedata"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SessionPhaseSection, measureddata),
		(ASN_TAG_CLASS_APPLICATION | (7019 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_measureddata_7,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"measureddata"
		},
};
static ber_tlv_tag_t asn_DEF_SessionPhaseSection_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_SessionPhaseSection_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (2337 << 2)), 0, 0, 0 }, /* handle at 726 */
    { (ASN_TAG_CLASS_APPLICATION | (2538 << 2)), 1, 0, 0 }, /* starttime at 729 */
    { (ASN_TAG_CLASS_APPLICATION | (2539 << 2)), 2, 0, 0 }, /* stoptime at 731 */
    { (ASN_TAG_CLASS_APPLICATION | (6499 << 2)), 3, 0, 0 }, /* placeholder at 733 */
    { (ASN_TAG_CLASS_APPLICATION | (7018 << 2)), 4, 0, 0 }, /* descriptivedata at 735 */
    { (ASN_TAG_CLASS_APPLICATION | (7019 << 2)), 5, 0, 0 } /* measureddata at 741 */
};
static asn_SEQUENCE_specifics_t asn_SPC_SessionPhaseSection_specs_1 = {
	sizeof(struct SessionPhaseSection),
	offsetof(struct SessionPhaseSection, _asn_ctx),
	asn_MAP_SessionPhaseSection_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SessionPhaseSection = {
	"SessionPhaseSection",
	"SessionPhaseSection",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SessionPhaseSection_tags_1,
	sizeof(asn_DEF_SessionPhaseSection_tags_1)
		/sizeof(asn_DEF_SessionPhaseSection_tags_1[0]), /* 1 */
	asn_DEF_SessionPhaseSection_tags_1,	/* Same as above */
	sizeof(asn_DEF_SessionPhaseSection_tags_1)
		/sizeof(asn_DEF_SessionPhaseSection_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SessionPhaseSection_1,
	6,	/* Elements count */
	&asn_SPC_SessionPhaseSection_specs_1	/* Additional specs */
};

