/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_SessionPhaseSection_H_
#define	_SessionPhaseSection_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Handle.h"
#include "AbsoluteTime.h"
#include "Placeholder.h"
#include "DescriptiveDataSection.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MeasuredDataSection;

/* SessionPhaseSection */
typedef struct SessionPhaseSection {
	Handle_t	 handle;
	AbsoluteTime_t	 starttime;
	AbsoluteTime_t	 stoptime;
	Placeholder_t	*placeholder	/* OPTIONAL */;
	DescriptiveDataSection_t	 descriptivedata;
	struct SessionPhaseSection__measureddata {
		A_SEQUENCE_OF(struct MeasuredDataSection) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} measureddata;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SessionPhaseSection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SessionPhaseSection;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "MeasuredDataSection.h"

#endif	/* _SessionPhaseSection_H_ */
