/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_SimpleColour_H_
#define	_SimpleColour_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SimpleColour {
	SimpleColour_colblack	= 0,
	SimpleColour_colred	= 1,
	SimpleColour_colgreen	= 2,
	SimpleColour_colyellow	= 3,
	SimpleColour_colblue	= 4,
	SimpleColour_colmagenta	= 5,
	SimpleColour_colcyan	= 6,
	SimpleColour_colwhite	= 7
} e_SimpleColour;

/* SimpleColour */
typedef INTEGER_t	 SimpleColour_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SimpleColour;
asn_struct_free_f SimpleColour_free;
asn_struct_print_f SimpleColour_print;
asn_constr_check_f SimpleColour_constraint;
ber_type_decoder_f SimpleColour_decode_ber;
der_type_encoder_f SimpleColour_encode_der;
xer_type_decoder_f SimpleColour_decode_xer;
xer_type_encoder_f SimpleColour_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SimpleColour_H_ */
