/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_StorageDataType_H_
#define	_StorageDataType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum StorageDataType {
	StorageDataType_unsigned	= 0,
	StorageDataType_signed	= 1,
	StorageDataType_ieee754float	= 2
} e_StorageDataType;

/* StorageDataType */
typedef INTEGER_t	 StorageDataType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_StorageDataType;
asn_struct_free_f StorageDataType_free;
asn_struct_print_f StorageDataType_print;
asn_constr_check_f StorageDataType_constraint;
ber_type_decoder_f StorageDataType_decode_ber;
der_type_encoder_f StorageDataType_encode_der;
xer_type_decoder_f StorageDataType_decode_xer;
xer_type_encoder_f StorageDataType_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _StorageDataType_H_ */
