/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_SystemModel_H_
#define	_SystemModel_H_


#include <asn_application.h>

/* Including external dependencies */
#include "FEFString.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SystemModel */
typedef struct SystemModel {
	FEFString_t	 manufacturer;
	FEFString_t	 model_number;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SystemModel_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SystemModel;

#ifdef __cplusplus
}
#endif

#endif	/* _SystemModel_H_ */
