/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_UnitsOfMeasurementCode_H_
#define	_UnitsOfMeasurementCode_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UnitsOfMeasurementCode */
typedef INTEGER_t	 UnitsOfMeasurementCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UnitsOfMeasurementCode;
asn_struct_free_f UnitsOfMeasurementCode_free;
asn_struct_print_f UnitsOfMeasurementCode_print;
asn_constr_check_f UnitsOfMeasurementCode_constraint;
ber_type_decoder_f UnitsOfMeasurementCode_decode_ber;
der_type_encoder_f UnitsOfMeasurementCode_encode_der;
xer_type_decoder_f UnitsOfMeasurementCode_decode_xer;
xer_type_encoder_f UnitsOfMeasurementCode_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _UnitsOfMeasurementCode_H_ */
