/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_UnitCode_H_
#define	_UnitCode_H_


#include <asn_application.h>

/* Including external dependencies */
#include "UnitsOfMeasurementCode.h"

#ifdef __cplusplus
extern "C" {
#endif

/* UnitCode */
typedef UnitsOfMeasurementCode_t	 UnitCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UnitCode;
asn_struct_free_f UnitCode_free;
asn_struct_print_f UnitCode_print;
asn_constr_check_f UnitCode_constraint;
ber_type_decoder_f UnitCode_decode_ber;
der_type_encoder_f UnitCode_encode_der;
xer_type_decoder_f UnitCode_decode_xer;
xer_type_encoder_f UnitCode_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _UnitCode_H_ */
