/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#ifndef	_VirtualMedicalDeviceSection_H_
#define	_VirtualMedicalDeviceSection_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Handle.h"
#include "DeviceCode.h"
#include "FEFString.h"
#include <INTEGER.h>
#include "ParameterGroupCode.h"
#include "MsmtPrinciple.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SystemModel;
struct ProdSpecEntry;

/* VirtualMedicalDeviceSection */
typedef struct VirtualMedicalDeviceSection {
	Handle_t	 handle;
	DeviceCode_t	 devicetype;
	FEFString_t	*labelstring	/* OPTIONAL */;
	struct SystemModel	*vmdmodel	/* OPTIONAL */;
	struct VirtualMedicalDeviceSection__productionspecification {
		A_SEQUENCE_OF(struct ProdSpecEntry) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *productionspecification;
	INTEGER_t	*compatibilityid	/* OPTIONAL */;
	ParameterGroupCode_t	*parametergroup	/* OPTIONAL */;
	INTEGER_t	*position	/* OPTIONAL */;
	MsmtPrinciple_t	*measurementprinciple	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VirtualMedicalDeviceSection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VirtualMedicalDeviceSection;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SystemModel.h"
#include "ProdSpecEntry.h"

#endif	/* _VirtualMedicalDeviceSection_H_ */
