/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "FEF-IntermediateDraft"
 * 	found in "../annexb-snacc-122001.asn1"
 */

#include <asn_internal.h>

#include "VirtualMedicalDeviceSection.h"

static asn_TYPE_member_t asn_MBR_productionspecification_6[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ProdSpecEntry,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_productionspecification_tags_6[] = {
	(ASN_TAG_CLASS_APPLICATION | (2349 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_productionspecification_specs_6 = {
	sizeof(struct VirtualMedicalDeviceSection__productionspecification),
	offsetof(struct VirtualMedicalDeviceSection__productionspecification, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_productionspecification_6 = {
	"productionspecification",
	"productionspecification",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_productionspecification_tags_6,
	sizeof(asn_DEF_productionspecification_tags_6)
		/sizeof(asn_DEF_productionspecification_tags_6[0]) - 1, /* 1 */
	asn_DEF_productionspecification_tags_6,	/* Same as above */
	sizeof(asn_DEF_productionspecification_tags_6)
		/sizeof(asn_DEF_productionspecification_tags_6[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_productionspecification_6,
	1,	/* Single element */
	&asn_SPC_productionspecification_specs_6	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_VirtualMedicalDeviceSection_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct VirtualMedicalDeviceSection, handle),
		(ASN_TAG_CLASS_APPLICATION | (2337 << 2)),
		0,
		&asn_DEF_Handle,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"handle"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct VirtualMedicalDeviceSection, devicetype),
		(ASN_TAG_CLASS_APPLICATION | (2351 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DeviceCode,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"devicetype"
		},
	{ ATF_POINTER, 7, offsetof(struct VirtualMedicalDeviceSection, labelstring),
		(ASN_TAG_CLASS_APPLICATION | (2343 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FEFString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"labelstring"
		},
	{ ATF_POINTER, 6, offsetof(struct VirtualMedicalDeviceSection, vmdmodel),
		(ASN_TAG_CLASS_APPLICATION | (2344 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SystemModel,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"vmdmodel"
		},
	{ ATF_POINTER, 5, offsetof(struct VirtualMedicalDeviceSection, productionspecification),
		(ASN_TAG_CLASS_APPLICATION | (2349 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_productionspecification_6,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"productionspecification"
		},
	{ ATF_POINTER, 4, offsetof(struct VirtualMedicalDeviceSection, compatibilityid),
		(ASN_TAG_CLASS_APPLICATION | (2336 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"compatibilityid"
		},
	{ ATF_POINTER, 3, offsetof(struct VirtualMedicalDeviceSection, parametergroup),
		(ASN_TAG_CLASS_APPLICATION | (2346 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ParameterGroupCode,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"parametergroup"
		},
	{ ATF_POINTER, 2, offsetof(struct VirtualMedicalDeviceSection, position),
		(ASN_TAG_CLASS_APPLICATION | (2348 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"position"
		},
	{ ATF_POINTER, 1, offsetof(struct VirtualMedicalDeviceSection, measurementprinciple),
		(ASN_TAG_CLASS_APPLICATION | (2560 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MsmtPrinciple,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"measurementprinciple"
		},
};
static ber_tlv_tag_t asn_DEF_VirtualMedicalDeviceSection_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_VirtualMedicalDeviceSection_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (2336 << 2)), 5, 0, 0 }, /* compatibilityid at 632 */
    { (ASN_TAG_CLASS_APPLICATION | (2337 << 2)), 0, 0, 0 }, /* handle at 613 */
    { (ASN_TAG_CLASS_APPLICATION | (2343 << 2)), 2, 0, 0 }, /* labelstring at 619 */
    { (ASN_TAG_CLASS_APPLICATION | (2344 << 2)), 3, 0, 0 }, /* vmdmodel at 622 */
    { (ASN_TAG_CLASS_APPLICATION | (2346 << 2)), 6, 0, 0 }, /* parametergroup at 635 */
    { (ASN_TAG_CLASS_APPLICATION | (2348 << 2)), 7, 0, 0 }, /* position at 638 */
    { (ASN_TAG_CLASS_APPLICATION | (2349 << 2)), 4, 0, 0 }, /* productionspecification at 627 */
    { (ASN_TAG_CLASS_APPLICATION | (2351 << 2)), 1, 0, 0 }, /* devicetype at 616 */
    { (ASN_TAG_CLASS_APPLICATION | (2560 << 2)), 8, 0, 0 } /* measurementprinciple at 642 */
};
static asn_SEQUENCE_specifics_t asn_SPC_VirtualMedicalDeviceSection_specs_1 = {
	sizeof(struct VirtualMedicalDeviceSection),
	offsetof(struct VirtualMedicalDeviceSection, _asn_ctx),
	asn_MAP_VirtualMedicalDeviceSection_tag2el_1,
	9,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_VirtualMedicalDeviceSection = {
	"VirtualMedicalDeviceSection",
	"VirtualMedicalDeviceSection",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_VirtualMedicalDeviceSection_tags_1,
	sizeof(asn_DEF_VirtualMedicalDeviceSection_tags_1)
		/sizeof(asn_DEF_VirtualMedicalDeviceSection_tags_1[0]), /* 1 */
	asn_DEF_VirtualMedicalDeviceSection_tags_1,	/* Same as above */
	sizeof(asn_DEF_VirtualMedicalDeviceSection_tags_1)
		/sizeof(asn_DEF_VirtualMedicalDeviceSection_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_VirtualMedicalDeviceSection_1,
	9,	/* Elements count */
	&asn_SPC_VirtualMedicalDeviceSection_specs_1	/* Additional specs */
};

