/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_bsv_main_win (void)
{
  GtkWidget *bsv_main_win;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *menuitem4;
  GtkWidget *menuitem4_menu;
  GtkWidget *preferences_main;
  GtkWidget *image18;
  GtkWidget *separatormenuitem1;
  GtkWidget *quit1;
  GtkWidget *menuitem5;
  GtkWidget *menuitem5_menu;
  GtkWidget *preferences_driver;
  GtkWidget *image19;
  GtkWidget *information2;
  GtkWidget *handlebox1;
  GtkWidget *toolbar1;
  GtkWidget *start_but;
  GtkWidget *alignment1;
  GtkWidget *hbox24;
  GtkWidget *image20;
  GtkWidget *label10;
  GtkWidget *stop_but;
  GtkWidget *alignment2;
  GtkWidget *hbox25;
  GtkWidget *image21;
  GtkWidget *label11;
  GtkWidget *handlebox2;
  GtkWidget *toolbar2;
  GtkWidget *chansel_combo;
  GtkWidget *combo_entry1;
  GtkWidget *label12;
  GtkObject *mag_spinbut_adj;
  GtkWidget *mag_spinbut;
  GtkWidget *label13;
  GtkWidget *combo1;
  GtkWidget *combo_entry2;
  GtkWidget *apply_but;
  GtkWidget *hbox18;
  GtkWidget *drawingarea;
  GtkWidget *vscrollbar1;
  GtkWidget *statusbar;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  bsv_main_win = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (bsv_main_win), _("BSView"));
  gtk_window_set_default_size (GTK_WINDOW (bsv_main_win), 500, 300);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (bsv_main_win), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);

  menuitem4 = gtk_menu_item_new_with_mnemonic (_("_Viewer"));
  gtk_widget_show (menuitem4);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem4);

  menuitem4_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem4), menuitem4_menu);

  preferences_main = gtk_image_menu_item_new_with_mnemonic (_("_Preferences"));
  gtk_widget_show (preferences_main);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), preferences_main);

  image18 = gtk_image_new_from_stock ("gtk-preferences", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image18);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (preferences_main), image18);

  separatormenuitem1 = gtk_menu_item_new ();
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  quit1 = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (quit1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), quit1);

  menuitem5 = gtk_menu_item_new_with_mnemonic (_("_Driver"));
  gtk_widget_show (menuitem5);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem5);

  menuitem5_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem5), menuitem5_menu);

  preferences_driver = gtk_image_menu_item_new_with_mnemonic (_("_Preferences"));
  gtk_widget_show (preferences_driver);
  gtk_container_add (GTK_CONTAINER (menuitem5_menu), preferences_driver);

  image19 = gtk_image_new_from_stock ("gtk-preferences", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image19);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (preferences_driver), image19);

  information2 = gtk_image_menu_item_new_from_stock ("gtk-dialog-info", accel_group);
  gtk_widget_show (information2);
  gtk_container_add (GTK_CONTAINER (menuitem5_menu), information2);

  handlebox1 = gtk_handle_box_new ();
  gtk_widget_show (handlebox1);
  gtk_box_pack_start (GTK_BOX (vbox1), handlebox1, FALSE, FALSE, 0);

  toolbar1 = gtk_toolbar_new ();
  gtk_widget_show (toolbar1);
  gtk_container_add (GTK_CONTAINER (handlebox1), toolbar1);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_ICONS);

  start_but = gtk_button_new ();
  gtk_widget_show (start_but);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar1), start_but, _("Start Aquistion"), NULL);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (start_but), alignment1);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox24);

  image20 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox24), image20, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("_Start"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox24), label10, FALSE, FALSE, 0);

  stop_but = gtk_button_new ();
  gtk_widget_show (stop_but);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar1), stop_but, _("Stop Aquistion"), NULL);
  gtk_widget_set_sensitive (stop_but, FALSE);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (stop_but), alignment2);

  hbox25 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox25);

  image21 = gtk_image_new_from_stock ("gtk-no", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox25), image21, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("St_op"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox25), label11, FALSE, FALSE, 0);

  handlebox2 = gtk_handle_box_new ();
  gtk_widget_show (handlebox2);
  gtk_box_pack_start (GTK_BOX (vbox1), handlebox2, FALSE, FALSE, 0);

  toolbar2 = gtk_toolbar_new ();
  gtk_widget_show (toolbar2);
  gtk_container_add (GTK_CONTAINER (handlebox2), toolbar2);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar2), GTK_TOOLBAR_ICONS);

  chansel_combo = gtk_combo_box_new_text();
  gtk_widget_show(chansel_combo);
  gtk_toolbar_append_widget(GTK_TOOLBAR(toolbar2), chansel_combo, NULL, NULL);
  gtk_widget_set_sensitive(chansel_combo, FALSE);		

/*
  chansel_combo = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (chansel_combo)->popwin),
                     "GladeParentKey", chansel_combo);
  gtk_widget_show (chansel_combo);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar2), chansel_combo, NULL, NULL);
  gtk_widget_set_sensitive (chansel_combo, FALSE);

  combo_entry1 = GTK_COMBO (chansel_combo)->entry;
  gtk_widget_show (combo_entry1);
*/

  label12 = gtk_label_new (_(" Mag in %: "));
  gtk_widget_show (label12);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar2), label12, NULL, NULL);

  mag_spinbut_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  mag_spinbut = gtk_spin_button_new (GTK_ADJUSTMENT (mag_spinbut_adj), 1, 0);
  gtk_widget_show (mag_spinbut);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar2), mag_spinbut, NULL, NULL);
  gtk_widget_set_sensitive (mag_spinbut, FALSE);

  label13 = gtk_label_new (_(" Notch: "));
  gtk_widget_show (label13);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar2), label13, NULL, NULL);

  combo1 = gtk_combo_box_new_text();
  gtk_widget_show(combo1);
  gtk_toolbar_append_widget(GTK_TOOLBAR(toolbar2), combo1, NULL, NULL);
  gtk_widget_set_sensitive(combo1, FALSE);
	  
/*
  combo1 = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo1)->popwin),
                     "GladeParentKey", combo1);
  gtk_widget_show (combo1);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar2), combo1, NULL, NULL);

  combo_entry2 = GTK_COMBO (combo1)->entry;
  gtk_widget_show (combo_entry2);
*/

  apply_but = gtk_button_new_from_stock ("gtk-apply");
  gtk_widget_show (apply_but);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar2), apply_but, _("Start Aquistion"), NULL);
  gtk_widget_set_sensitive (apply_but, FALSE);

  hbox18 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox18);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox18, TRUE, TRUE, 0);

  drawingarea = gtk_drawing_area_new ();
  gtk_widget_show (drawingarea);
  gtk_box_pack_start (GTK_BOX (hbox18), drawingarea, TRUE, TRUE, 0);

  vscrollbar1 = gtk_vscrollbar_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 10, 1, 1, 1)));
  gtk_widget_show (vscrollbar1);
  gtk_box_pack_start (GTK_BOX (hbox18), vscrollbar1, FALSE, TRUE, 0);
  gtk_widget_set_sensitive (vscrollbar1, FALSE);

  statusbar = gtk_statusbar_new ();
  gtk_widget_show (statusbar);
  gtk_box_pack_start (GTK_BOX (vbox1), statusbar, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) bsv_main_win, "delete-event",
                    G_CALLBACK (main_quit),
                    NULL);
  g_signal_connect ((gpointer) preferences_main, "activate",
                    G_CALLBACK (run_viewer_preference_dlg),
                    NULL);
  g_signal_connect ((gpointer) quit1, "activate",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) preferences_driver, "activate",
                    G_CALLBACK (run_driver_perferences_dlg),
                    NULL);
  g_signal_connect ((gpointer) information2, "activate",
                    G_CALLBACK (run_driver_info_dlg),
                    NULL);
  g_signal_connect ((gpointer) start_but, "clicked",
                    G_CALLBACK (start_acquistion),
                    NULL);
  g_signal_connect ((gpointer) stop_but, "clicked",
                    G_CALLBACK (stop_acquistion),
                    NULL);
  g_signal_connect ((gpointer) apply_but, "clicked",
                    G_CALLBACK (apply_but_clicked),
                    NULL);
  g_signal_connect ((gpointer) drawingarea, "expose_event",
                    G_CALLBACK (resize_area),
                    NULL);
  g_signal_connect ((gpointer) vscrollbar1, "value_changed",
                    G_CALLBACK (vsbar_value_changed),
                    NULL);
  g_signal_connect ((gpointer) chansel_combo, "changed",
  					G_CALLBACK (chansel_combo_changed),
					NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (bsv_main_win, bsv_main_win, "bsv_main_win");
  GLADE_HOOKUP_OBJECT (bsv_main_win, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (bsv_main_win, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (bsv_main_win, menuitem4, "menuitem4");
  GLADE_HOOKUP_OBJECT (bsv_main_win, menuitem4_menu, "menuitem4_menu");
  GLADE_HOOKUP_OBJECT (bsv_main_win, preferences_main, "preferences_main");
  GLADE_HOOKUP_OBJECT (bsv_main_win, image18, "image18");
  GLADE_HOOKUP_OBJECT (bsv_main_win, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (bsv_main_win, quit1, "quit1");
  GLADE_HOOKUP_OBJECT (bsv_main_win, menuitem5, "menuitem5");
  GLADE_HOOKUP_OBJECT (bsv_main_win, menuitem5_menu, "menuitem5_menu");
  GLADE_HOOKUP_OBJECT (bsv_main_win, preferences_driver, "preferences_driver");
  GLADE_HOOKUP_OBJECT (bsv_main_win, image19, "image19");
  GLADE_HOOKUP_OBJECT (bsv_main_win, information2, "information2");
  GLADE_HOOKUP_OBJECT (bsv_main_win, handlebox1, "handlebox1");
  GLADE_HOOKUP_OBJECT (bsv_main_win, toolbar1, "toolbar1");
  GLADE_HOOKUP_OBJECT (bsv_main_win, start_but, "start_but");
  GLADE_HOOKUP_OBJECT (bsv_main_win, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (bsv_main_win, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (bsv_main_win, image20, "image20");
  GLADE_HOOKUP_OBJECT (bsv_main_win, label10, "label10");
  GLADE_HOOKUP_OBJECT (bsv_main_win, stop_but, "stop_but");
  GLADE_HOOKUP_OBJECT (bsv_main_win, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (bsv_main_win, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (bsv_main_win, image21, "image21");
  GLADE_HOOKUP_OBJECT (bsv_main_win, label11, "label11");
  GLADE_HOOKUP_OBJECT (bsv_main_win, handlebox2, "handlebox2");
  GLADE_HOOKUP_OBJECT (bsv_main_win, toolbar2, "toolbar2");
  GLADE_HOOKUP_OBJECT (bsv_main_win, chansel_combo, "chansel_combo");
//  GLADE_HOOKUP_OBJECT (bsv_main_win, combo_entry1, "combo_entry1");
  GLADE_HOOKUP_OBJECT (bsv_main_win, label12, "label12");
  GLADE_HOOKUP_OBJECT (bsv_main_win, mag_spinbut, "mag_spinbut");
  GLADE_HOOKUP_OBJECT (bsv_main_win, label13, "label13");
  GLADE_HOOKUP_OBJECT (bsv_main_win, combo1, "combo1");
//  GLADE_HOOKUP_OBJECT (bsv_main_win, combo_entry2, "combo_entry2");
  GLADE_HOOKUP_OBJECT (bsv_main_win, apply_but, "apply_but");
  GLADE_HOOKUP_OBJECT (bsv_main_win, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (bsv_main_win, drawingarea, "drawingarea");
  GLADE_HOOKUP_OBJECT (bsv_main_win, vscrollbar1, "vscrollbar1");
  GLADE_HOOKUP_OBJECT (bsv_main_win, statusbar, "statusbar");

  gtk_window_add_accel_group (GTK_WINDOW (bsv_main_win), accel_group);

  return bsv_main_win;
}

GtkWidget*
create_bsv_viewer_pref_dlg (void)
{
  GtkWidget *bsv_viewer_pref_dlg;
  GtkWidget *dialog_vbox1;
  GtkWidget *notebook1;
  GtkWidget *vbox2;
  GtkWidget *hbox19;
  GtkWidget *label3;
  GtkObject *chanperscreen_spinb_adj;
  GtkWidget *chanperscreen_spinb;
  GtkWidget *hbox20;
  GtkWidget *label4;
  GtkObject *hrange_spinb_adj;
  GtkWidget *hrange_spinb;
  GtkWidget *label5;
  GtkWidget *label1;
  GtkWidget *vbox3;
  GtkWidget *hbox21;
  GtkWidget *label6;
  GtkWidget *logfile_entry;
  GtkWidget *button15;
  GtkWidget *image17;
  GtkWidget *hbox22;
  GtkWidget *label7;
  GtkWidget *patid_entry;
  GtkWidget *hbox23;
  GtkWidget *label8;
  GtkWidget *recid_entry;
  GtkWidget *label2;
  GtkWidget *dialog_action_area1;
  GtkWidget *okbutton1;

  bsv_viewer_pref_dlg = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (bsv_viewer_pref_dlg), _("Viewer Preferences"));

  dialog_vbox1 = GTK_DIALOG (bsv_viewer_pref_dlg)->vbox;
  gtk_widget_show (dialog_vbox1);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), notebook1, TRUE, TRUE, 0);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox2);

  hbox19 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox19);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox19, FALSE, TRUE, 0);

  label3 = gtk_label_new (_("Channels per Screen: "));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox19), label3, FALSE, FALSE, 0);

  chanperscreen_spinb_adj = gtk_adjustment_new (1, 1, 100, 1, 10, 10);
  chanperscreen_spinb = gtk_spin_button_new (GTK_ADJUSTMENT (chanperscreen_spinb_adj), 1, 0);
  gtk_widget_show (chanperscreen_spinb);
  gtk_box_pack_start (GTK_BOX (hbox19), chanperscreen_spinb, FALSE, TRUE, 0);

  hbox20 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox20);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox20, FALSE, TRUE, 0);

  label4 = gtk_label_new (_("Horizontal Time Range: "));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox20), label4, FALSE, FALSE, 0);

  hrange_spinb_adj = gtk_adjustment_new (1, 1, 100, 1, 10, 10);
  hrange_spinb = gtk_spin_button_new (GTK_ADJUSTMENT (hrange_spinb_adj), 1, 0);
  gtk_widget_show (hrange_spinb);
  gtk_box_pack_start (GTK_BOX (hbox20), hrange_spinb, FALSE, TRUE, 0);

  label5 = gtk_label_new (_(" sec"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox20), label5, FALSE, FALSE, 0);

  label1 = gtk_label_new (_("Viewer"));
  gtk_widget_show (label1);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label1);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox3);

  hbox21 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox21);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox21, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox21), 2);

  label6 = gtk_label_new (_("GDF Logfile: "));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox21), label6, FALSE, FALSE, 0);

  logfile_entry = gtk_entry_new ();
  gtk_widget_show (logfile_entry);
  gtk_box_pack_start (GTK_BOX (hbox21), logfile_entry, TRUE, TRUE, 0);

  button15 = gtk_button_new ();
  gtk_widget_show (button15);
  gtk_box_pack_start (GTK_BOX (hbox21), button15, FALSE, FALSE, 0);

  image17 = gtk_image_new_from_stock ("gtk-floppy", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_container_add (GTK_CONTAINER (button15), image17);

  hbox22 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox22);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox22, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox22), 2);

  label7 = gtk_label_new (_("Patient ID: "));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox22), label7, FALSE, FALSE, 0);

  patid_entry = gtk_entry_new ();
  gtk_widget_show (patid_entry);
  gtk_box_pack_start (GTK_BOX (hbox22), patid_entry, TRUE, TRUE, 0);

  hbox23 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox23);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox23, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox23), 2);

  label8 = gtk_label_new (_("Record ID: "));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox23), label8, FALSE, FALSE, 0);

  recid_entry = gtk_entry_new ();
  gtk_widget_show (recid_entry);
  gtk_box_pack_start (GTK_BOX (hbox23), recid_entry, TRUE, TRUE, 0);

  label2 = gtk_label_new (_("Logfile"));
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label2);

  dialog_action_area1 = GTK_DIALOG (bsv_viewer_pref_dlg)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  okbutton1 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (bsv_viewer_pref_dlg), okbutton1, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton1, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) bsv_viewer_pref_dlg, "delete_event",
                    G_CALLBACK (update_viewer_settings),
                    NULL);
  g_signal_connect ((gpointer) button15, "clicked",
                    G_CALLBACK (show_fs_dlg),
                    NULL);
  g_signal_connect ((gpointer) okbutton1, "clicked",
                    G_CALLBACK (update_viewer_settings_but),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (bsv_viewer_pref_dlg, bsv_viewer_pref_dlg, "bsv_viewer_pref_dlg");
  GLADE_HOOKUP_OBJECT_NO_REF (bsv_viewer_pref_dlg, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (bsv_viewer_pref_dlg, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (bsv_viewer_pref_dlg, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (bsv_viewer_pref_dlg, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (bsv_viewer_pref_dlg, label3, "label3");
  GLADE_HOOKUP_OBJECT (bsv_viewer_pref_dlg, chanperscreen_spinb, "chanperscreen_spinb");
  GLADE_HOOKUP_OBJECT (bsv_viewer_pref_dlg, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (bsv_viewer_pref_dlg, label4, "label4");
  GLADE_HOOKUP_OBJECT (bsv_viewer_pref_dlg, hrange_spinb, "hrange_spinb");
  GLADE_HOOKUP_OBJECT (bsv_viewer_pref_dlg, label5, "label5");
  GLADE_HOOKUP_OBJECT (bsv_viewer_pref_dlg, label1, "label1");
  GLADE_HOOKUP_OBJECT (bsv_viewer_pref_dlg, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (bsv_viewer_pref_dlg, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (bsv_viewer_pref_dlg, label6, "label6");
  GLADE_HOOKUP_OBJECT (bsv_viewer_pref_dlg, logfile_entry, "logfile_entry");
  GLADE_HOOKUP_OBJECT (bsv_viewer_pref_dlg, button15, "button15");
  GLADE_HOOKUP_OBJECT (bsv_viewer_pref_dlg, image17, "image17");
  GLADE_HOOKUP_OBJECT (bsv_viewer_pref_dlg, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (bsv_viewer_pref_dlg, label7, "label7");
  GLADE_HOOKUP_OBJECT (bsv_viewer_pref_dlg, patid_entry, "patid_entry");
  GLADE_HOOKUP_OBJECT (bsv_viewer_pref_dlg, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (bsv_viewer_pref_dlg, label8, "label8");
  GLADE_HOOKUP_OBJECT (bsv_viewer_pref_dlg, recid_entry, "recid_entry");
  GLADE_HOOKUP_OBJECT (bsv_viewer_pref_dlg, label2, "label2");
  GLADE_HOOKUP_OBJECT_NO_REF (bsv_viewer_pref_dlg, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (bsv_viewer_pref_dlg, okbutton1, "okbutton1");

  return bsv_viewer_pref_dlg;
}

GtkWidget*
create_bsv_fs_dlg (void)
{
  GtkWidget *bsv_fs_dlg;
  GtkWidget *ok_button1;
  GtkWidget *cancel_button1;

  bsv_fs_dlg = gtk_file_selection_new (_("Select File"));
  gtk_container_set_border_width (GTK_CONTAINER (bsv_fs_dlg), 10);

  ok_button1 = GTK_FILE_SELECTION (bsv_fs_dlg)->ok_button;
  gtk_widget_show (ok_button1);
  GTK_WIDGET_SET_FLAGS (ok_button1, GTK_CAN_DEFAULT);

  cancel_button1 = GTK_FILE_SELECTION (bsv_fs_dlg)->cancel_button;
  gtk_widget_show (cancel_button1);
  GTK_WIDGET_SET_FLAGS (cancel_button1, GTK_CAN_DEFAULT);

  g_signal_connect_swapped ((gpointer) bsv_fs_dlg, "delete_event",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (bsv_fs_dlg));
  g_signal_connect ((gpointer) ok_button1, "clicked",
                    G_CALLBACK (update_logfile),
                    NULL);
  g_signal_connect_swapped ((gpointer) cancel_button1, "clicked",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (bsv_fs_dlg));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (bsv_fs_dlg, bsv_fs_dlg, "bsv_fs_dlg");
  GLADE_HOOKUP_OBJECT_NO_REF (bsv_fs_dlg, ok_button1, "ok_button1");
  GLADE_HOOKUP_OBJECT_NO_REF (bsv_fs_dlg, cancel_button1, "cancel_button1");

  return bsv_fs_dlg;
}

GtkWidget*
create_bsv_driver_info_dlg (void)
{
  GtkWidget *bsv_driver_info_dlg;
  GtkWidget *dialog_vbox2;
  GtkWidget *hbox26;
  GtkWidget *label_desc;
  GtkWidget *label_val;
  GtkWidget *dialog_action_area2;
  GtkWidget *okbutton2;

  bsv_driver_info_dlg = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (bsv_driver_info_dlg), _("Driver Information"));

  dialog_vbox2 = GTK_DIALOG (bsv_driver_info_dlg)->vbox;
  gtk_widget_show (dialog_vbox2);

  hbox26 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox26);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), hbox26, TRUE, TRUE, 0);

  label_desc = gtk_label_new (_("label14"));
  gtk_widget_show (label_desc);
  gtk_box_pack_start (GTK_BOX (hbox26), label_desc, TRUE, TRUE, 0);

  label_val = gtk_label_new (_("label15"));
  gtk_widget_show (label_val);
  gtk_box_pack_start (GTK_BOX (hbox26), label_val, TRUE, TRUE, 0);

  dialog_action_area2 = GTK_DIALOG (bsv_driver_info_dlg)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  okbutton2 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton2);
  gtk_dialog_add_action_widget (GTK_DIALOG (bsv_driver_info_dlg), okbutton2, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton2, GTK_CAN_DEFAULT);

  g_signal_connect_swapped ((gpointer) bsv_driver_info_dlg, "delete_event",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (bsv_driver_info_dlg));
  g_signal_connect_swapped ((gpointer) okbutton2, "clicked",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (bsv_driver_info_dlg));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (bsv_driver_info_dlg, bsv_driver_info_dlg, "bsv_driver_info_dlg");
  GLADE_HOOKUP_OBJECT_NO_REF (bsv_driver_info_dlg, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT (bsv_driver_info_dlg, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (bsv_driver_info_dlg, label_desc, "label_desc");
  GLADE_HOOKUP_OBJECT (bsv_driver_info_dlg, label_val, "label_val");
  GLADE_HOOKUP_OBJECT_NO_REF (bsv_driver_info_dlg, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (bsv_driver_info_dlg, okbutton2, "okbutton2");

  return bsv_driver_info_dlg;
}

