/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_bsv_main_win (void);
GtkWidget* create_bsv_viewer_pref_dlg (void);
GtkWidget* create_bsv_fs_dlg (void);
GtkWidget* create_bsv_driver_info_dlg (void);
