.TH SigViewer 1
.SH NAME
SigViewer - a viewing and scoring tools for biomedical signals. 

.SH SYNOPSIS	
.R sigviewer


.SH DESCRIPTION 
SigViewer is a viewing and scoring software for biomedical signal data. 
A number of data formats (including EDF, BDF, GDF, BrainVision, BCI2000, CFWB,  
HL7aECG, SCP_ECG (EN1064), MFER, ACQ, CNT(Neuroscan), DEMG, EGI, 
EEG1100, FAMOS, SigmaPLpro, TMS32) are supported. The complete list of supported 
file formats is available at http://hci.tugraz.at/schloegl/biosig/TESTED .  
	
.SH AUTHOR
Alois Schloegl 
	
.SH REPORTING BUGS 
Report bugs to <biosig-general@lists.sourceforge.net>
	
.SH COPYRIGHT
Copyright (C) 2008,2010 Alois Schloegl   
License GPLv3+:  GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This  is  free  software:  you  are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

.SH RESOURCES
http://biosig.sf.net	
	
	
