/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_dialog1 (void)
{
  GtkWidget *dialog1;
  GtkWidget *dialog_vbox1;
  GtkWidget *notebook1;
  GtkWidget *vbox1;
  GtkWidget *hbox3;
  GtkWidget *ch1_chk;
  GtkWidget *label6;
  GtkWidget *ch1_hp_entry;
  GtkWidget *label7;
  GtkWidget *ch1_tp_entry;
  GtkWidget *label41;
  GtkWidget *ch1_rng_combo;
  GtkWidget *label63;
  GtkWidget *ch1_ref_combo;
  GtkWidget *hbox4;
  GtkWidget *ch2_chk;
  GtkWidget *label8;
  GtkWidget *ch2_hp_entry;
  GtkWidget *label9;
  GtkWidget *ch2_tp_entry;
  GtkWidget *label42;
  GtkWidget *ch2_rng_combo;
  GtkWidget *label64;
  GtkWidget *ch2_ref_combo;
  GtkWidget *hbox5;
  GtkWidget *ch3_chk;
  GtkWidget *label10;
  GtkWidget *ch3_hp_entry;
  GtkWidget *label11;
  GtkWidget *ch3_tp_entry;
  GtkWidget *label43;
  GtkWidget *ch3_rng_combo;
  GtkWidget *label65;
  GtkWidget *ch3_ref_combo;
  GtkWidget *hbox6;
  GtkWidget *ch4_chk;
  GtkWidget *label12;
  GtkWidget *ch4_hp_entry;
  GtkWidget *label13;
  GtkWidget *ch4_tp_entry;
  GtkWidget *label44;
  GtkWidget *ch4_rng_combo;
  GtkWidget *label66;
  GtkWidget *ch4_ref_combo;
  GtkWidget *label1;
  GtkWidget *vbox3;
  GtkWidget *hbox7;
  GtkWidget *ch5_chk;
  GtkWidget *label17;
  GtkWidget *ch5_hp_entry;
  GtkWidget *label18;
  GtkWidget *ch5_tp_entry;
  GtkWidget *label45;
  GtkWidget *ch5_rng_combo;
  GtkWidget *label67;
  GtkWidget *ch5_ref_combo;
  GtkWidget *hbox8;
  GtkWidget *ch6_chk;
  GtkWidget *label19;
  GtkWidget *ch6_hp_entry;
  GtkWidget *label20;
  GtkWidget *ch6_tp_entry;
  GtkWidget *label46;
  GtkWidget *ch6_rng_combo;
  GtkWidget *label68;
  GtkWidget *ch6_ref_combo;
  GtkWidget *hbox9;
  GtkWidget *ch7_chk;
  GtkWidget *label21;
  GtkWidget *ch7_hp_entry;
  GtkWidget *label22;
  GtkWidget *ch7_tp_entry;
  GtkWidget *label47;
  GtkWidget *ch7_rng_combo;
  GtkWidget *label69;
  GtkWidget *ch7_ref_combo;
  GtkWidget *hbox10;
  GtkWidget *ch8_chk;
  GtkWidget *label23;
  GtkWidget *ch8_hp_entry;
  GtkWidget *label24;
  GtkWidget *ch8_tp_entry;
  GtkWidget *label48;
  GtkWidget *ch8_rng_combo;
  GtkWidget *label70;
  GtkWidget *ch8_ref_combo;
  GtkWidget *label2;
  GtkWidget *vbox4;
  GtkWidget *hbox11;
  GtkWidget *ch9_chk;
  GtkWidget *label25;
  GtkWidget *ch9_hp_entry;
  GtkWidget *label26;
  GtkWidget *ch9_tp_entry;
  GtkWidget *label49;
  GtkWidget *ch9_rng_combo;
  GtkWidget *label71;
  GtkWidget *ch9_ref_combo;
  GtkWidget *hbox12;
  GtkWidget *ch10_chk;
  GtkWidget *label27;
  GtkWidget *ch10_hp_entry;
  GtkWidget *label28;
  GtkWidget *ch10_tp_entry;
  GtkWidget *label50;
  GtkWidget *ch10_rng_combo;
  GtkWidget *label72;
  GtkWidget *ch10_ref_combo;
  GtkWidget *hbox13;
  GtkWidget *ch11_chk;
  GtkWidget *label29;
  GtkWidget *ch11_hp_entry;
  GtkWidget *label30;
  GtkWidget *ch11_tp_entry;
  GtkWidget *label51;
  GtkWidget *ch11_rng_combo;
  GtkWidget *label73;
  GtkWidget *ch11_ref_combo;
  GtkWidget *hbox14;
  GtkWidget *ch12_chk;
  GtkWidget *label31;
  GtkWidget *ch12_hp_entry;
  GtkWidget *label32;
  GtkWidget *ch12_tp_entry;
  GtkWidget *label52;
  GtkWidget *ch12_rng_combo;
  GtkWidget *label74;
  GtkWidget *ch12_ref_combo;
  GtkWidget *label14;
  GtkWidget *vbox5;
  GtkWidget *hbox15;
  GtkWidget *ch13_chk;
  GtkWidget *label33;
  GtkWidget *ch13_hp_entry;
  GtkWidget *label34;
  GtkWidget *ch13_tp_entry;
  GtkWidget *label53;
  GtkWidget *ch13_rng_combo;
  GtkWidget *label59;
  GtkWidget *ch13_ref_combo;
  GtkWidget *hbox16;
  GtkWidget *ch14_chk;
  GtkWidget *label35;
  GtkWidget *ch14_hp_entry;
  GtkWidget *label36;
  GtkWidget *ch14_tp_entry;
  GtkWidget *label54;
  GtkWidget *ch14_rng_combo;
  GtkWidget *label60;
  GtkWidget *ch14_ref_combo;
  GtkWidget *hbox17;
  GtkWidget *ch15_chk;
  GtkWidget *label37;
  GtkWidget *ch15_hp_entry;
  GtkWidget *label38;
  GtkWidget *ch15_tp_entry;
  GtkWidget *label55;
  GtkWidget *ch15_rng_combo;
  GtkWidget *label61;
  GtkWidget *ch15_ref_combo;
  GtkWidget *hbox18;
  GtkWidget *ch16_chk;
  GtkWidget *label39;
  GtkWidget *ch16_hp_entry;
  GtkWidget *label40;
  GtkWidget *ch16_tp_entry;
  GtkWidget *label56;
  GtkWidget *ch16_rng_combo;
  GtkWidget *label62;
  GtkWidget *ch16_ref_combo;
  GtkWidget *label15;
  GtkWidget *vbox6;
  GtkWidget *hbox19;
  GtkWidget *label57;
  GtkWidget *srate_combo;
  GtkWidget *label16;
  GtkWidget *dialog_action_area1;
  GtkWidget *okbutton1;

  dialog1 = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog1), _("NI 6024E config"));

  dialog_vbox1 = GTK_DIALOG (dialog1)->vbox;
  gtk_widget_show (dialog_vbox1);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), notebook1, TRUE, TRUE, 0);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox1);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox3, FALSE, FALSE, 0);

  ch1_chk = gtk_check_button_new_with_mnemonic (_("Channel 01"));
  gtk_widget_show (ch1_chk);
  gtk_box_pack_start (GTK_BOX (hbox3), ch1_chk, FALSE, FALSE, 0);

  label6 = gtk_label_new (_("   HP:"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox3), label6, FALSE, FALSE, 0);

  ch1_hp_entry = gtk_entry_new ();
  gtk_widget_show (ch1_hp_entry);
  gtk_box_pack_start (GTK_BOX (hbox3), ch1_hp_entry, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch1_hp_entry, FALSE);
  gtk_entry_set_width_chars (GTK_ENTRY (ch1_hp_entry), 4);

  label7 = gtk_label_new (_("Hz  TP:"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox3), label7, FALSE, FALSE, 0);

  ch1_tp_entry = gtk_entry_new ();
  gtk_widget_show (ch1_tp_entry);
  gtk_box_pack_start (GTK_BOX (hbox3), ch1_tp_entry, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch1_tp_entry, FALSE);
  gtk_entry_set_width_chars (GTK_ENTRY (ch1_tp_entry), 4);

  label41 = gtk_label_new (_("Hz  Range:"));
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox3), label41, FALSE, FALSE, 0);

  ch1_rng_combo = gtk_combo_box_new_text();
  gtk_widget_show (ch1_rng_combo);
  gtk_box_pack_start (GTK_BOX (hbox3), ch1_rng_combo, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch1_rng_combo, FALSE);

  label63 = gtk_label_new (_("  Ref:"));
  gtk_widget_show (label63);
  gtk_box_pack_start (GTK_BOX (hbox3), label63, FALSE, FALSE, 0);

  ch1_ref_combo = gtk_combo_box_new_text();
  gtk_widget_show (ch1_ref_combo);
  gtk_box_pack_start (GTK_BOX (hbox3), ch1_ref_combo, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch1_ref_combo, FALSE);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox4);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox4, FALSE, FALSE, 0);

  ch2_chk = gtk_check_button_new_with_mnemonic (_("Channel 02"));
  gtk_widget_show (ch2_chk);
  gtk_box_pack_start (GTK_BOX (hbox4), ch2_chk, FALSE, FALSE, 0);

  label8 = gtk_label_new (_("   HP:"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox4), label8, FALSE, FALSE, 0);

  ch2_hp_entry = gtk_entry_new ();
  gtk_widget_show (ch2_hp_entry);
  gtk_box_pack_start (GTK_BOX (hbox4), ch2_hp_entry, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch2_hp_entry, FALSE);
  gtk_entry_set_width_chars (GTK_ENTRY (ch2_hp_entry), 4);

  label9 = gtk_label_new (_("Hz  TP:"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox4), label9, FALSE, FALSE, 0);

  ch2_tp_entry = gtk_entry_new ();
  gtk_widget_show (ch2_tp_entry);
  gtk_box_pack_start (GTK_BOX (hbox4), ch2_tp_entry, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch2_tp_entry, FALSE);
  gtk_entry_set_width_chars (GTK_ENTRY (ch2_tp_entry), 4);

  label42 = gtk_label_new (_("Hz  Range:"));
  gtk_widget_show (label42);
  gtk_box_pack_start (GTK_BOX (hbox4), label42, FALSE, FALSE, 0);

  ch2_rng_combo = gtk_combo_box_new_text();
  gtk_widget_show (ch2_rng_combo);
  gtk_box_pack_start (GTK_BOX (hbox4), ch2_rng_combo, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch2_rng_combo, FALSE);

  label64 = gtk_label_new (_("  Ref:"));
  gtk_widget_show (label64);
  gtk_box_pack_start (GTK_BOX (hbox4), label64, FALSE, FALSE, 0);

  ch2_ref_combo = gtk_combo_box_new_text();
  gtk_widget_show (ch2_ref_combo);
  gtk_box_pack_start (GTK_BOX (hbox4), ch2_ref_combo, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch2_ref_combo, FALSE);

  hbox5 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox5);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox5, FALSE, FALSE, 0);

  ch3_chk = gtk_check_button_new_with_mnemonic (_("Channel 03"));
  gtk_widget_show (ch3_chk);
  gtk_box_pack_start (GTK_BOX (hbox5), ch3_chk, FALSE, FALSE, 0);

  label10 = gtk_label_new (_("   HP:"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox5), label10, FALSE, FALSE, 0);

  ch3_hp_entry = gtk_entry_new ();
  gtk_widget_show (ch3_hp_entry);
  gtk_box_pack_start (GTK_BOX (hbox5), ch3_hp_entry, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch3_hp_entry, FALSE);
  gtk_entry_set_width_chars (GTK_ENTRY (ch3_hp_entry), 4);

  label11 = gtk_label_new (_("Hz  TP:"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox5), label11, FALSE, FALSE, 0);

  ch3_tp_entry = gtk_entry_new ();
  gtk_widget_show (ch3_tp_entry);
  gtk_box_pack_start (GTK_BOX (hbox5), ch3_tp_entry, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch3_tp_entry, FALSE);
  gtk_entry_set_width_chars (GTK_ENTRY (ch3_tp_entry), 4);

  label43 = gtk_label_new (_("Hz  Range:"));
  gtk_widget_show (label43);
  gtk_box_pack_start (GTK_BOX (hbox5), label43, FALSE, FALSE, 0);

  ch3_rng_combo = gtk_combo_box_new_text();
  gtk_widget_show (ch3_rng_combo);
  gtk_box_pack_start (GTK_BOX (hbox5), ch3_rng_combo, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch3_rng_combo, FALSE);

  label65 = gtk_label_new (_("  Ref:"));
  gtk_widget_show (label65);
  gtk_box_pack_start (GTK_BOX (hbox5), label65, FALSE, FALSE, 0);

  ch3_ref_combo = gtk_combo_box_new_text();
  gtk_widget_show (ch3_ref_combo);
  gtk_box_pack_start (GTK_BOX (hbox5), ch3_ref_combo, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch3_ref_combo, FALSE);

  hbox6 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox6);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox6, FALSE, FALSE, 0);

  ch4_chk = gtk_check_button_new_with_mnemonic (_("Channel 04"));
  gtk_widget_show (ch4_chk);
  gtk_box_pack_start (GTK_BOX (hbox6), ch4_chk, FALSE, FALSE, 0);

  label12 = gtk_label_new (_("   HP:"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox6), label12, FALSE, FALSE, 0);

  ch4_hp_entry = gtk_entry_new ();
  gtk_widget_show (ch4_hp_entry);
  gtk_box_pack_start (GTK_BOX (hbox6), ch4_hp_entry, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch4_hp_entry, FALSE);
  gtk_entry_set_width_chars (GTK_ENTRY (ch4_hp_entry), 4);

  label13 = gtk_label_new (_("Hz  TP:"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox6), label13, FALSE, FALSE, 0);

  ch4_tp_entry = gtk_entry_new ();
  gtk_widget_show (ch4_tp_entry);
  gtk_box_pack_start (GTK_BOX (hbox6), ch4_tp_entry, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch4_tp_entry, FALSE);
  gtk_entry_set_width_chars (GTK_ENTRY (ch4_tp_entry), 4);

  label44 = gtk_label_new (_("Hz  Range:"));
  gtk_widget_show (label44);
  gtk_box_pack_start (GTK_BOX (hbox6), label44, FALSE, FALSE, 0);

  ch4_rng_combo = gtk_combo_box_new_text();
  gtk_widget_show (ch4_rng_combo);
  gtk_box_pack_start (GTK_BOX (hbox6), ch4_rng_combo, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch4_rng_combo, FALSE);

  label66 = gtk_label_new (_("  Ref:"));
  gtk_widget_show (label66);
  gtk_box_pack_start (GTK_BOX (hbox6), label66, FALSE, FALSE, 0);

  ch4_ref_combo = gtk_combo_box_new_text();
  gtk_widget_show (ch4_ref_combo);
  gtk_box_pack_start (GTK_BOX (hbox6), ch4_ref_combo, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch4_ref_combo, FALSE);

  label1 = gtk_label_new (_("AIN (1 to 4)"));
  gtk_widget_show (label1);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label1);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox3);

  hbox7 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox7);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox7, FALSE, FALSE, 0);

  ch5_chk = gtk_check_button_new_with_mnemonic (_("Channel 05"));
  gtk_widget_show (ch5_chk);
  gtk_box_pack_start (GTK_BOX (hbox7), ch5_chk, FALSE, FALSE, 0);

  label17 = gtk_label_new (_("   HP:"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox7), label17, FALSE, FALSE, 0);

  ch5_hp_entry = gtk_entry_new ();
  gtk_widget_show (ch5_hp_entry);
  gtk_box_pack_start (GTK_BOX (hbox7), ch5_hp_entry, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch5_hp_entry, FALSE);
  gtk_entry_set_width_chars (GTK_ENTRY (ch5_hp_entry), 4);

  label18 = gtk_label_new (_("Hz  TP:"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox7), label18, FALSE, FALSE, 0);

  ch5_tp_entry = gtk_entry_new ();
  gtk_widget_show (ch5_tp_entry);
  gtk_box_pack_start (GTK_BOX (hbox7), ch5_tp_entry, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch5_tp_entry, FALSE);
  gtk_entry_set_width_chars (GTK_ENTRY (ch5_tp_entry), 4);

  label45 = gtk_label_new (_("Hz  Range:"));
  gtk_widget_show (label45);
  gtk_box_pack_start (GTK_BOX (hbox7), label45, FALSE, FALSE, 0);

  ch5_rng_combo = gtk_combo_box_new_text();
  gtk_widget_show (ch5_rng_combo);
  gtk_box_pack_start (GTK_BOX (hbox7), ch5_rng_combo, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch5_rng_combo, FALSE);

  label67 = gtk_label_new (_("  Ref:"));
  gtk_widget_show (label67);
  gtk_box_pack_start (GTK_BOX (hbox7), label67, FALSE, FALSE, 0);

  ch5_ref_combo = gtk_combo_box_new_text();
  gtk_widget_show (ch5_ref_combo);
  gtk_box_pack_start (GTK_BOX (hbox7), ch5_ref_combo, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch5_ref_combo, FALSE);

  hbox8 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox8);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox8, FALSE, FALSE, 0);

  ch6_chk = gtk_check_button_new_with_mnemonic (_("Channel 06"));
  gtk_widget_show (ch6_chk);
  gtk_box_pack_start (GTK_BOX (hbox8), ch6_chk, FALSE, FALSE, 0);

  label19 = gtk_label_new (_("   HP:"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox8), label19, FALSE, FALSE, 0);

  ch6_hp_entry = gtk_entry_new ();
  gtk_widget_show (ch6_hp_entry);
  gtk_box_pack_start (GTK_BOX (hbox8), ch6_hp_entry, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch6_hp_entry, FALSE);
  gtk_entry_set_width_chars (GTK_ENTRY (ch6_hp_entry), 4);

  label20 = gtk_label_new (_("Hz  TP:"));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox8), label20, FALSE, FALSE, 0);

  ch6_tp_entry = gtk_entry_new ();
  gtk_widget_show (ch6_tp_entry);
  gtk_box_pack_start (GTK_BOX (hbox8), ch6_tp_entry, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch6_tp_entry, FALSE);
  gtk_entry_set_width_chars (GTK_ENTRY (ch6_tp_entry), 4);

  label46 = gtk_label_new (_("Hz  Range:"));
  gtk_widget_show (label46);
  gtk_box_pack_start (GTK_BOX (hbox8), label46, FALSE, FALSE, 0);

  ch6_rng_combo = gtk_combo_box_new_text();
  gtk_widget_show (ch6_rng_combo);
  gtk_box_pack_start (GTK_BOX (hbox8), ch6_rng_combo, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch6_rng_combo, FALSE);

  label68 = gtk_label_new (_("  Ref:"));
  gtk_widget_show (label68);
  gtk_box_pack_start (GTK_BOX (hbox8), label68, FALSE, FALSE, 0);

  ch6_ref_combo = gtk_combo_box_new_text();
  gtk_widget_show (ch6_ref_combo);
  gtk_box_pack_start (GTK_BOX (hbox8), ch6_ref_combo, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch6_ref_combo, FALSE);

  hbox9 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox9);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox9, FALSE, FALSE, 0);

  ch7_chk = gtk_check_button_new_with_mnemonic (_("Channel 07"));
  gtk_widget_show (ch7_chk);
  gtk_box_pack_start (GTK_BOX (hbox9), ch7_chk, FALSE, FALSE, 0);

  label21 = gtk_label_new (_("   HP:"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox9), label21, FALSE, FALSE, 0);

  ch7_hp_entry = gtk_entry_new ();
  gtk_widget_show (ch7_hp_entry);
  gtk_box_pack_start (GTK_BOX (hbox9), ch7_hp_entry, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch7_hp_entry, FALSE);
  gtk_entry_set_width_chars (GTK_ENTRY (ch7_hp_entry), 4);

  label22 = gtk_label_new (_("Hz  TP:"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox9), label22, FALSE, FALSE, 0);

  ch7_tp_entry = gtk_entry_new ();
  gtk_widget_show (ch7_tp_entry);
  gtk_box_pack_start (GTK_BOX (hbox9), ch7_tp_entry, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch7_tp_entry, FALSE);
  gtk_entry_set_width_chars (GTK_ENTRY (ch7_tp_entry), 4);

  label47 = gtk_label_new (_("Hz  Range:"));
  gtk_widget_show (label47);
  gtk_box_pack_start (GTK_BOX (hbox9), label47, FALSE, FALSE, 0);

  ch7_rng_combo = gtk_combo_box_new_text();
  gtk_widget_show (ch7_rng_combo);
  gtk_box_pack_start (GTK_BOX (hbox9), ch7_rng_combo, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch7_rng_combo, FALSE);

  label69 = gtk_label_new (_("  Ref:"));
  gtk_widget_show (label69);
  gtk_box_pack_start (GTK_BOX (hbox9), label69, FALSE, FALSE, 0);

  ch7_ref_combo = gtk_combo_box_new_text();
  gtk_widget_show (ch7_ref_combo);
  gtk_box_pack_start (GTK_BOX (hbox9), ch7_ref_combo, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch7_ref_combo, FALSE);

  hbox10 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox10);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox10, FALSE, FALSE, 0);

  ch8_chk = gtk_check_button_new_with_mnemonic (_("Channel 08"));
  gtk_widget_show (ch8_chk);
  gtk_box_pack_start (GTK_BOX (hbox10), ch8_chk, FALSE, FALSE, 0);

  label23 = gtk_label_new (_("   HP:"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox10), label23, FALSE, FALSE, 0);

  ch8_hp_entry = gtk_entry_new ();
  gtk_widget_show (ch8_hp_entry);
  gtk_box_pack_start (GTK_BOX (hbox10), ch8_hp_entry, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch8_hp_entry, FALSE);
  gtk_entry_set_width_chars (GTK_ENTRY (ch8_hp_entry), 4);

  label24 = gtk_label_new (_("Hz  TP:"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox10), label24, FALSE, FALSE, 0);

  ch8_tp_entry = gtk_entry_new ();
  gtk_widget_show (ch8_tp_entry);
  gtk_box_pack_start (GTK_BOX (hbox10), ch8_tp_entry, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch8_tp_entry, FALSE);
  gtk_entry_set_width_chars (GTK_ENTRY (ch8_tp_entry), 4);

  label48 = gtk_label_new (_("Hz  Range:"));
  gtk_widget_show (label48);
  gtk_box_pack_start (GTK_BOX (hbox10), label48, FALSE, FALSE, 0);

  ch8_rng_combo = gtk_combo_box_new_text();
  gtk_widget_show (ch8_rng_combo);
  gtk_box_pack_start (GTK_BOX (hbox10), ch8_rng_combo, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch8_rng_combo, FALSE);

  label70 = gtk_label_new (_("  Ref:"));
  gtk_widget_show (label70);
  gtk_box_pack_start (GTK_BOX (hbox10), label70, FALSE, FALSE, 0);

  ch8_ref_combo = gtk_combo_box_new_text();
  gtk_widget_show (ch8_ref_combo);
  gtk_box_pack_start (GTK_BOX (hbox10), ch8_ref_combo, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch8_ref_combo, FALSE);

  label2 = gtk_label_new (_("AIN (5 to 8)"));
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label2);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox4);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox4);

  hbox11 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox11);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox11, FALSE, FALSE, 0);

  ch9_chk = gtk_check_button_new_with_mnemonic (_("Channel 09"));
  gtk_widget_show (ch9_chk);
  gtk_box_pack_start (GTK_BOX (hbox11), ch9_chk, FALSE, FALSE, 0);

  label25 = gtk_label_new (_("   HP:"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox11), label25, FALSE, FALSE, 0);

  ch9_hp_entry = gtk_entry_new ();
  gtk_widget_show (ch9_hp_entry);
  gtk_box_pack_start (GTK_BOX (hbox11), ch9_hp_entry, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch9_hp_entry, FALSE);
  gtk_entry_set_width_chars (GTK_ENTRY (ch9_hp_entry), 4);

  label26 = gtk_label_new (_("Hz  TP:"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox11), label26, FALSE, FALSE, 0);

  ch9_tp_entry = gtk_entry_new ();
  gtk_widget_show (ch9_tp_entry);
  gtk_box_pack_start (GTK_BOX (hbox11), ch9_tp_entry, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch9_tp_entry, FALSE);
  gtk_entry_set_width_chars (GTK_ENTRY (ch9_tp_entry), 4);

  label49 = gtk_label_new (_("Hz  Range:"));
  gtk_widget_show (label49);
  gtk_box_pack_start (GTK_BOX (hbox11), label49, FALSE, FALSE, 0);

  ch9_rng_combo = gtk_combo_box_new_text();
  gtk_widget_show (ch9_rng_combo);
  gtk_box_pack_start (GTK_BOX (hbox11), ch9_rng_combo, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch9_rng_combo, FALSE);

  label71 = gtk_label_new (_("  Ref:"));
  gtk_widget_show (label71);
  gtk_box_pack_start (GTK_BOX (hbox11), label71, FALSE, FALSE, 0);

  ch9_ref_combo = gtk_combo_box_new_text();
  gtk_widget_show (ch9_ref_combo);
  gtk_box_pack_start (GTK_BOX (hbox11), ch9_ref_combo, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch9_ref_combo, FALSE);

  hbox12 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox12);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox12, FALSE, FALSE, 0);

  ch10_chk = gtk_check_button_new_with_mnemonic (_("Channel 10"));
  gtk_widget_show (ch10_chk);
  gtk_box_pack_start (GTK_BOX (hbox12), ch10_chk, FALSE, FALSE, 0);

  label27 = gtk_label_new (_("   HP:"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox12), label27, FALSE, FALSE, 0);

  ch10_hp_entry = gtk_entry_new ();
  gtk_widget_show (ch10_hp_entry);
  gtk_box_pack_start (GTK_BOX (hbox12), ch10_hp_entry, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch10_hp_entry, FALSE);
  gtk_entry_set_width_chars (GTK_ENTRY (ch10_hp_entry), 4);

  label28 = gtk_label_new (_("Hz  TP:"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox12), label28, FALSE, FALSE, 0);

  ch10_tp_entry = gtk_entry_new ();
  gtk_widget_show (ch10_tp_entry);
  gtk_box_pack_start (GTK_BOX (hbox12), ch10_tp_entry, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch10_tp_entry, FALSE);
  gtk_entry_set_width_chars (GTK_ENTRY (ch10_tp_entry), 4);

  label50 = gtk_label_new (_("Hz  Range:"));
  gtk_widget_show (label50);
  gtk_box_pack_start (GTK_BOX (hbox12), label50, FALSE, FALSE, 0);

  ch10_rng_combo = gtk_combo_box_new_text();
  gtk_widget_show (ch10_rng_combo);
  gtk_box_pack_start (GTK_BOX (hbox12), ch10_rng_combo, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch10_rng_combo, FALSE);

  label72 = gtk_label_new (_("  Ref:"));
  gtk_widget_show (label72);
  gtk_box_pack_start (GTK_BOX (hbox12), label72, FALSE, FALSE, 0);

  ch10_ref_combo = gtk_combo_box_new_text();
  gtk_widget_show (ch10_ref_combo);
  gtk_box_pack_start (GTK_BOX (hbox12), ch10_ref_combo, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch10_ref_combo, FALSE);

  hbox13 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox13);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox13, FALSE, FALSE, 0);

  ch11_chk = gtk_check_button_new_with_mnemonic (_("Channel 11"));
  gtk_widget_show (ch11_chk);
  gtk_box_pack_start (GTK_BOX (hbox13), ch11_chk, FALSE, FALSE, 0);

  label29 = gtk_label_new (_("   HP:"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox13), label29, FALSE, FALSE, 0);

  ch11_hp_entry = gtk_entry_new ();
  gtk_widget_show (ch11_hp_entry);
  gtk_box_pack_start (GTK_BOX (hbox13), ch11_hp_entry, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch11_hp_entry, FALSE);
  gtk_entry_set_width_chars (GTK_ENTRY (ch11_hp_entry), 4);

  label30 = gtk_label_new (_("Hz  TP:"));
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox13), label30, FALSE, FALSE, 0);

  ch11_tp_entry = gtk_entry_new ();
  gtk_widget_show (ch11_tp_entry);
  gtk_box_pack_start (GTK_BOX (hbox13), ch11_tp_entry, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch11_tp_entry, FALSE);
  gtk_entry_set_width_chars (GTK_ENTRY (ch11_tp_entry), 4);

  label51 = gtk_label_new (_("Hz  Range:"));
  gtk_widget_show (label51);
  gtk_box_pack_start (GTK_BOX (hbox13), label51, FALSE, FALSE, 0);

  ch11_rng_combo = gtk_combo_box_new_text();
  gtk_widget_show (ch11_rng_combo);
  gtk_box_pack_start (GTK_BOX (hbox13), ch11_rng_combo, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch11_rng_combo, FALSE);

  label73 = gtk_label_new (_("  Ref:"));
  gtk_widget_show (label73);
  gtk_box_pack_start (GTK_BOX (hbox13), label73, FALSE, FALSE, 0);

  ch11_ref_combo = gtk_combo_box_new_text();
  gtk_widget_show (ch11_ref_combo);
  gtk_box_pack_start (GTK_BOX (hbox13), ch11_ref_combo, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch11_ref_combo, FALSE);

  hbox14 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox14);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox14, FALSE, FALSE, 0);

  ch12_chk = gtk_check_button_new_with_mnemonic (_("Channel 12"));
  gtk_widget_show (ch12_chk);
  gtk_box_pack_start (GTK_BOX (hbox14), ch12_chk, FALSE, FALSE, 0);

  label31 = gtk_label_new (_("   HP:"));
  gtk_widget_show (label31);
  gtk_box_pack_start (GTK_BOX (hbox14), label31, FALSE, FALSE, 0);

  ch12_hp_entry = gtk_entry_new ();
  gtk_widget_show (ch12_hp_entry);
  gtk_box_pack_start (GTK_BOX (hbox14), ch12_hp_entry, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch12_hp_entry, FALSE);
  gtk_entry_set_width_chars (GTK_ENTRY (ch12_hp_entry), 4);

  label32 = gtk_label_new (_("Hz  TP:"));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox14), label32, FALSE, FALSE, 0);

  ch12_tp_entry = gtk_entry_new ();
  gtk_widget_show (ch12_tp_entry);
  gtk_box_pack_start (GTK_BOX (hbox14), ch12_tp_entry, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch12_tp_entry, FALSE);
  gtk_entry_set_width_chars (GTK_ENTRY (ch12_tp_entry), 4);

  label52 = gtk_label_new (_("Hz  Range:"));
  gtk_widget_show (label52);
  gtk_box_pack_start (GTK_BOX (hbox14), label52, FALSE, FALSE, 0);

  ch12_rng_combo = gtk_combo_box_new_text();
  gtk_widget_show (ch12_rng_combo);
  gtk_box_pack_start (GTK_BOX (hbox14), ch12_rng_combo, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch12_rng_combo, FALSE);

  label74 = gtk_label_new (_("  Ref:"));
  gtk_widget_show (label74);
  gtk_box_pack_start (GTK_BOX (hbox14), label74, FALSE, FALSE, 0);

  ch12_ref_combo = gtk_combo_box_new_text();
  gtk_widget_show (ch12_ref_combo);
  gtk_box_pack_start (GTK_BOX (hbox14), ch12_ref_combo, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch12_ref_combo, FALSE);

  label14 = gtk_label_new (_("AIN (9 to 12)"));
  gtk_widget_show (label14);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label14);

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox5);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox5);

  hbox15 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox15);
  gtk_box_pack_start (GTK_BOX (vbox5), hbox15, FALSE, FALSE, 0);

  ch13_chk = gtk_check_button_new_with_mnemonic (_("Channel 13"));
  gtk_widget_show (ch13_chk);
  gtk_box_pack_start (GTK_BOX (hbox15), ch13_chk, FALSE, FALSE, 0);

  label33 = gtk_label_new (_("   HP:"));
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (hbox15), label33, FALSE, FALSE, 0);

  ch13_hp_entry = gtk_entry_new ();
  gtk_widget_show (ch13_hp_entry);
  gtk_box_pack_start (GTK_BOX (hbox15), ch13_hp_entry, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch13_hp_entry, FALSE);
  gtk_entry_set_width_chars (GTK_ENTRY (ch13_hp_entry), 4);

  label34 = gtk_label_new (_("Hz  TP:"));
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (hbox15), label34, FALSE, FALSE, 0);

  ch13_tp_entry = gtk_entry_new ();
  gtk_widget_show (ch13_tp_entry);
  gtk_box_pack_start (GTK_BOX (hbox15), ch13_tp_entry, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch13_tp_entry, FALSE);
  gtk_entry_set_width_chars (GTK_ENTRY (ch13_tp_entry), 4);

  label53 = gtk_label_new (_("Hz  Range:"));
  gtk_widget_show (label53);
  gtk_box_pack_start (GTK_BOX (hbox15), label53, FALSE, FALSE, 0);

  ch13_rng_combo = gtk_combo_box_new_text();
  gtk_widget_show (ch13_rng_combo);
  gtk_box_pack_start (GTK_BOX (hbox15), ch13_rng_combo, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch13_rng_combo, FALSE);

  label59 = gtk_label_new (_("  Ref:"));
  gtk_widget_show (label59);
  gtk_box_pack_start (GTK_BOX (hbox15), label59, FALSE, FALSE, 0);

  ch13_ref_combo = gtk_combo_box_new_text();
  gtk_widget_show (ch13_ref_combo);
  gtk_box_pack_start (GTK_BOX (hbox15), ch13_ref_combo, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch13_ref_combo, FALSE);

  hbox16 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox16);
  gtk_box_pack_start (GTK_BOX (vbox5), hbox16, FALSE, FALSE, 0);

  ch14_chk = gtk_check_button_new_with_mnemonic (_("Channel 14"));
  gtk_widget_show (ch14_chk);
  gtk_box_pack_start (GTK_BOX (hbox16), ch14_chk, FALSE, FALSE, 0);

  label35 = gtk_label_new (_("   HP:"));
  gtk_widget_show (label35);
  gtk_box_pack_start (GTK_BOX (hbox16), label35, FALSE, FALSE, 0);

  ch14_hp_entry = gtk_entry_new ();
  gtk_widget_show (ch14_hp_entry);
  gtk_box_pack_start (GTK_BOX (hbox16), ch14_hp_entry, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch14_hp_entry, FALSE);
  gtk_entry_set_width_chars (GTK_ENTRY (ch14_hp_entry), 4);

  label36 = gtk_label_new (_("Hz  TP:"));
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox16), label36, FALSE, FALSE, 0);

  ch14_tp_entry = gtk_entry_new ();
  gtk_widget_show (ch14_tp_entry);
  gtk_box_pack_start (GTK_BOX (hbox16), ch14_tp_entry, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch14_tp_entry, FALSE);
  gtk_entry_set_width_chars (GTK_ENTRY (ch14_tp_entry), 4);

  label54 = gtk_label_new (_("Hz  Range:"));
  gtk_widget_show (label54);
  gtk_box_pack_start (GTK_BOX (hbox16), label54, FALSE, FALSE, 0);

  ch14_rng_combo = gtk_combo_box_new_text();
  gtk_widget_show (ch14_rng_combo);
  gtk_box_pack_start (GTK_BOX (hbox16), ch14_rng_combo, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch14_rng_combo, FALSE);

  label60 = gtk_label_new (_("  Ref:"));
  gtk_widget_show (label60);
  gtk_box_pack_start (GTK_BOX (hbox16), label60, FALSE, FALSE, 0);

  ch14_ref_combo = gtk_combo_box_new_text();
  gtk_widget_show (ch14_ref_combo);
  gtk_box_pack_start (GTK_BOX (hbox16), ch14_ref_combo, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch14_ref_combo, FALSE);

  hbox17 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox17);
  gtk_box_pack_start (GTK_BOX (vbox5), hbox17, FALSE, FALSE, 0);

  ch15_chk = gtk_check_button_new_with_mnemonic (_("Channel 15"));
  gtk_widget_show (ch15_chk);
  gtk_box_pack_start (GTK_BOX (hbox17), ch15_chk, FALSE, FALSE, 0);

  label37 = gtk_label_new (_("   HP:"));
  gtk_widget_show (label37);
  gtk_box_pack_start (GTK_BOX (hbox17), label37, FALSE, FALSE, 0);

  ch15_hp_entry = gtk_entry_new ();
  gtk_widget_show (ch15_hp_entry);
  gtk_box_pack_start (GTK_BOX (hbox17), ch15_hp_entry, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch15_hp_entry, FALSE);
  gtk_entry_set_width_chars (GTK_ENTRY (ch15_hp_entry), 4);

  label38 = gtk_label_new (_("Hz  TP:"));
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox17), label38, FALSE, FALSE, 0);

  ch15_tp_entry = gtk_entry_new ();
  gtk_widget_show (ch15_tp_entry);
  gtk_box_pack_start (GTK_BOX (hbox17), ch15_tp_entry, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch15_tp_entry, FALSE);
  gtk_entry_set_width_chars (GTK_ENTRY (ch15_tp_entry), 4);

  label55 = gtk_label_new (_("Hz  Range:"));
  gtk_widget_show (label55);
  gtk_box_pack_start (GTK_BOX (hbox17), label55, FALSE, FALSE, 0);

  ch15_rng_combo = gtk_combo_box_new_text();
  gtk_widget_show (ch15_rng_combo);
  gtk_box_pack_start (GTK_BOX (hbox17), ch15_rng_combo, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch15_rng_combo, FALSE);

  label61 = gtk_label_new (_("  Ref:"));
  gtk_widget_show (label61);
  gtk_box_pack_start (GTK_BOX (hbox17), label61, FALSE, FALSE, 0);

  ch15_ref_combo = gtk_combo_box_new_text();
  gtk_widget_show (ch15_ref_combo);
  gtk_box_pack_start (GTK_BOX (hbox17), ch15_ref_combo, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch15_ref_combo, FALSE);

  hbox18 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox18);
  gtk_box_pack_start (GTK_BOX (vbox5), hbox18, FALSE, FALSE, 0);

  ch16_chk = gtk_check_button_new_with_mnemonic (_("Channel 16"));
  gtk_widget_show (ch16_chk);
  gtk_box_pack_start (GTK_BOX (hbox18), ch16_chk, FALSE, FALSE, 0);

  label39 = gtk_label_new (_("   HP:"));
  gtk_widget_show (label39);
  gtk_box_pack_start (GTK_BOX (hbox18), label39, FALSE, FALSE, 0);

  ch16_hp_entry = gtk_entry_new ();
  gtk_widget_show (ch16_hp_entry);
  gtk_box_pack_start (GTK_BOX (hbox18), ch16_hp_entry, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch16_hp_entry, FALSE);
  gtk_entry_set_width_chars (GTK_ENTRY (ch16_hp_entry), 4);

  label40 = gtk_label_new (_("Hz  TP:"));
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (hbox18), label40, FALSE, FALSE, 0);

  ch16_tp_entry = gtk_entry_new ();
  gtk_widget_show (ch16_tp_entry);
  gtk_box_pack_start (GTK_BOX (hbox18), ch16_tp_entry, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch16_tp_entry, FALSE);
  gtk_entry_set_width_chars (GTK_ENTRY (ch16_tp_entry), 4);

  label56 = gtk_label_new (_("Hz  Range:"));
  gtk_widget_show (label56);
  gtk_box_pack_start (GTK_BOX (hbox18), label56, FALSE, FALSE, 0);

  ch16_rng_combo = gtk_combo_box_new_text();
  gtk_widget_show (ch16_rng_combo);
  gtk_box_pack_start (GTK_BOX (hbox18), ch16_rng_combo, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch16_rng_combo, FALSE);

  label62 = gtk_label_new (_("  Ref:"));
  gtk_widget_show (label62);
  gtk_box_pack_start (GTK_BOX (hbox18), label62, FALSE, FALSE, 0);

  ch16_ref_combo = gtk_combo_box_new_text();
  gtk_widget_show (ch16_ref_combo);
  gtk_box_pack_start (GTK_BOX (hbox18), ch16_ref_combo, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (ch16_ref_combo, FALSE);

  label15 = gtk_label_new (_("AIN (13 to 16)"));
  gtk_widget_show (label15);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label15);

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox6);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox6);

  hbox19 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox19);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox19, FALSE, FALSE, 0);

  label57 = gtk_label_new (_("Sampling Rate: "));
  gtk_widget_show (label57);
  gtk_box_pack_start (GTK_BOX (hbox19), label57, FALSE, FALSE, 0);

  srate_combo = gtk_combo_box_new_text();
  gtk_widget_show (srate_combo);
  gtk_box_pack_start (GTK_BOX (hbox19), srate_combo, FALSE, FALSE, 0);

  label16 = gtk_label_new (_("General"));
  gtk_widget_show (label16);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 4), label16);

  dialog_action_area1 = GTK_DIALOG (dialog1)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  okbutton1 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog1), okbutton1, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton1, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) dialog1, "delete_event",
                    G_CALLBACK (update_config),
                    NULL);
  g_signal_connect ((gpointer) ch1_chk, "toggled",
                    G_CALLBACK (on_ch1_chk_toggled),
                    NULL);
  g_signal_connect ((gpointer) ch2_chk, "toggled",
                    G_CALLBACK (on_ch2_chk_toggled),
                    NULL);
  g_signal_connect ((gpointer) ch3_chk, "toggled",
                    G_CALLBACK (on_ch3_chk_toggled),
                    NULL);
  g_signal_connect ((gpointer) ch4_chk, "toggled",
                    G_CALLBACK (on_ch4_chk_toggled),
                    NULL);
  g_signal_connect ((gpointer) ch5_chk, "toggled",
                    G_CALLBACK (on_ch5_chk_toggled),
                    NULL);
  g_signal_connect ((gpointer) ch6_chk, "toggled",
                    G_CALLBACK (on_ch6_chk_toggled),
                    NULL);
  g_signal_connect ((gpointer) ch7_chk, "toggled",
                    G_CALLBACK (on_ch7_chk_toggled),
                    NULL);
  g_signal_connect ((gpointer) ch8_chk, "toggled",
                    G_CALLBACK (on_ch8_chk_toggled),
                    NULL);
  g_signal_connect ((gpointer) ch9_chk, "toggled",
                    G_CALLBACK (on_ch9_chk_toggled),
                    NULL);
  g_signal_connect ((gpointer) ch10_chk, "toggled",
                    G_CALLBACK (on_ch10_chk_toggled),
                    NULL);
  g_signal_connect ((gpointer) ch11_chk, "toggled",
                    G_CALLBACK (on_ch11_chk_toggled),
                    NULL);
  g_signal_connect ((gpointer) ch12_chk, "toggled",
                    G_CALLBACK (on_ch12_chk_toggled),
                    NULL);
  g_signal_connect ((gpointer) ch13_chk, "toggled",
                    G_CALLBACK (on_ch13_chk_toggled),
                    NULL);
  g_signal_connect ((gpointer) ch14_chk, "toggled",
                    G_CALLBACK (on_ch14_chk_toggled),
                    NULL);
  g_signal_connect ((gpointer) ch15_chk, "toggled",
                    G_CALLBACK (on_ch15_chk_toggled),
                    NULL);
  g_signal_connect ((gpointer) ch16_chk, "toggled",
                    G_CALLBACK (on_ch16_chk_toggled),
                    NULL);
  g_signal_connect ((gpointer) okbutton1, "clicked",
                    G_CALLBACK (update_config),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog1, dialog1, "dialog1");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog1, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (dialog1, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (dialog1, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (dialog1, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (dialog1, ch1_chk, "ch1_chk");
  GLADE_HOOKUP_OBJECT (dialog1, label6, "label6");
  GLADE_HOOKUP_OBJECT (dialog1, ch1_hp_entry, "ch1_hp_entry");
  GLADE_HOOKUP_OBJECT (dialog1, label7, "label7");
  GLADE_HOOKUP_OBJECT (dialog1, ch1_tp_entry, "ch1_tp_entry");
  GLADE_HOOKUP_OBJECT (dialog1, label41, "label41");
  GLADE_HOOKUP_OBJECT (dialog1, ch1_rng_combo, "ch1_rng_combo");
  GLADE_HOOKUP_OBJECT (dialog1, label63, "label63");
  GLADE_HOOKUP_OBJECT (dialog1, ch1_ref_combo, "ch1_ref_combo");
  GLADE_HOOKUP_OBJECT (dialog1, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (dialog1, ch2_chk, "ch2_chk");
  GLADE_HOOKUP_OBJECT (dialog1, label8, "label8");
  GLADE_HOOKUP_OBJECT (dialog1, ch2_hp_entry, "ch2_hp_entry");
  GLADE_HOOKUP_OBJECT (dialog1, label9, "label9");
  GLADE_HOOKUP_OBJECT (dialog1, ch2_tp_entry, "ch2_tp_entry");
  GLADE_HOOKUP_OBJECT (dialog1, label42, "label42");
  GLADE_HOOKUP_OBJECT (dialog1, ch2_rng_combo, "ch2_rng_combo");
  GLADE_HOOKUP_OBJECT (dialog1, label64, "label64");
  GLADE_HOOKUP_OBJECT (dialog1, ch2_ref_combo, "ch2_ref_combo");
  GLADE_HOOKUP_OBJECT (dialog1, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (dialog1, ch3_chk, "ch3_chk");
  GLADE_HOOKUP_OBJECT (dialog1, label10, "label10");
  GLADE_HOOKUP_OBJECT (dialog1, ch3_hp_entry, "ch3_hp_entry");
  GLADE_HOOKUP_OBJECT (dialog1, label11, "label11");
  GLADE_HOOKUP_OBJECT (dialog1, ch3_tp_entry, "ch3_tp_entry");
  GLADE_HOOKUP_OBJECT (dialog1, label43, "label43");
  GLADE_HOOKUP_OBJECT (dialog1, ch3_rng_combo, "ch3_rng_combo");
  GLADE_HOOKUP_OBJECT (dialog1, label65, "label65");
  GLADE_HOOKUP_OBJECT (dialog1, ch3_ref_combo, "ch3_ref_combo");
  GLADE_HOOKUP_OBJECT (dialog1, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (dialog1, ch4_chk, "ch4_chk");
  GLADE_HOOKUP_OBJECT (dialog1, label12, "label12");
  GLADE_HOOKUP_OBJECT (dialog1, ch4_hp_entry, "ch4_hp_entry");
  GLADE_HOOKUP_OBJECT (dialog1, label13, "label13");
  GLADE_HOOKUP_OBJECT (dialog1, ch4_tp_entry, "ch4_tp_entry");
  GLADE_HOOKUP_OBJECT (dialog1, label44, "label44");
  GLADE_HOOKUP_OBJECT (dialog1, ch4_rng_combo, "ch4_rng_combo");
  GLADE_HOOKUP_OBJECT (dialog1, label66, "label66");
  GLADE_HOOKUP_OBJECT (dialog1, ch4_ref_combo, "ch4_ref_combo");
  GLADE_HOOKUP_OBJECT (dialog1, label1, "label1");
  GLADE_HOOKUP_OBJECT (dialog1, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (dialog1, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (dialog1, ch5_chk, "ch5_chk");
  GLADE_HOOKUP_OBJECT (dialog1, label17, "label17");
  GLADE_HOOKUP_OBJECT (dialog1, ch5_hp_entry, "ch5_hp_entry");
  GLADE_HOOKUP_OBJECT (dialog1, label18, "label18");
  GLADE_HOOKUP_OBJECT (dialog1, ch5_tp_entry, "ch5_tp_entry");
  GLADE_HOOKUP_OBJECT (dialog1, label45, "label45");
  GLADE_HOOKUP_OBJECT (dialog1, ch5_rng_combo, "ch5_rng_combo");
  GLADE_HOOKUP_OBJECT (dialog1, label67, "label67");
  GLADE_HOOKUP_OBJECT (dialog1, ch5_ref_combo, "ch5_ref_combo");
  GLADE_HOOKUP_OBJECT (dialog1, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (dialog1, ch6_chk, "ch6_chk");
  GLADE_HOOKUP_OBJECT (dialog1, label19, "label19");
  GLADE_HOOKUP_OBJECT (dialog1, ch6_hp_entry, "ch6_hp_entry");
  GLADE_HOOKUP_OBJECT (dialog1, label20, "label20");
  GLADE_HOOKUP_OBJECT (dialog1, ch6_tp_entry, "ch6_tp_entry");
  GLADE_HOOKUP_OBJECT (dialog1, label46, "label46");
  GLADE_HOOKUP_OBJECT (dialog1, ch6_rng_combo, "ch6_rng_combo");
  GLADE_HOOKUP_OBJECT (dialog1, label68, "label68");
  GLADE_HOOKUP_OBJECT (dialog1, ch6_ref_combo, "ch6_ref_combo");
  GLADE_HOOKUP_OBJECT (dialog1, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (dialog1, ch7_chk, "ch7_chk");
  GLADE_HOOKUP_OBJECT (dialog1, label21, "label21");
  GLADE_HOOKUP_OBJECT (dialog1, ch7_hp_entry, "ch7_hp_entry");
  GLADE_HOOKUP_OBJECT (dialog1, label22, "label22");
  GLADE_HOOKUP_OBJECT (dialog1, ch7_tp_entry, "ch7_tp_entry");
  GLADE_HOOKUP_OBJECT (dialog1, label47, "label47");
  GLADE_HOOKUP_OBJECT (dialog1, ch7_rng_combo, "ch7_rng_combo");
  GLADE_HOOKUP_OBJECT (dialog1, label69, "label69");
  GLADE_HOOKUP_OBJECT (dialog1, ch7_ref_combo, "ch7_ref_combo");
  GLADE_HOOKUP_OBJECT (dialog1, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (dialog1, ch8_chk, "ch8_chk");
  GLADE_HOOKUP_OBJECT (dialog1, label23, "label23");
  GLADE_HOOKUP_OBJECT (dialog1, ch8_hp_entry, "ch8_hp_entry");
  GLADE_HOOKUP_OBJECT (dialog1, label24, "label24");
  GLADE_HOOKUP_OBJECT (dialog1, ch8_tp_entry, "ch8_tp_entry");
  GLADE_HOOKUP_OBJECT (dialog1, label48, "label48");
  GLADE_HOOKUP_OBJECT (dialog1, ch8_rng_combo, "ch8_rng_combo");
  GLADE_HOOKUP_OBJECT (dialog1, label70, "label70");
  GLADE_HOOKUP_OBJECT (dialog1, ch8_ref_combo, "ch8_ref_combo");
  GLADE_HOOKUP_OBJECT (dialog1, label2, "label2");
  GLADE_HOOKUP_OBJECT (dialog1, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (dialog1, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (dialog1, ch9_chk, "ch9_chk");
  GLADE_HOOKUP_OBJECT (dialog1, label25, "label25");
  GLADE_HOOKUP_OBJECT (dialog1, ch9_hp_entry, "ch9_hp_entry");
  GLADE_HOOKUP_OBJECT (dialog1, label26, "label26");
  GLADE_HOOKUP_OBJECT (dialog1, ch9_tp_entry, "ch9_tp_entry");
  GLADE_HOOKUP_OBJECT (dialog1, label49, "label49");
  GLADE_HOOKUP_OBJECT (dialog1, ch9_rng_combo, "ch9_rng_combo");
  GLADE_HOOKUP_OBJECT (dialog1, label71, "label71");
  GLADE_HOOKUP_OBJECT (dialog1, ch9_ref_combo, "ch9_ref_combo");
  GLADE_HOOKUP_OBJECT (dialog1, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (dialog1, ch10_chk, "ch10_chk");
  GLADE_HOOKUP_OBJECT (dialog1, label27, "label27");
  GLADE_HOOKUP_OBJECT (dialog1, ch10_hp_entry, "ch10_hp_entry");
  GLADE_HOOKUP_OBJECT (dialog1, label28, "label28");
  GLADE_HOOKUP_OBJECT (dialog1, ch10_tp_entry, "ch10_tp_entry");
  GLADE_HOOKUP_OBJECT (dialog1, label50, "label50");
  GLADE_HOOKUP_OBJECT (dialog1, ch10_rng_combo, "ch10_rng_combo");
  GLADE_HOOKUP_OBJECT (dialog1, label72, "label72");
  GLADE_HOOKUP_OBJECT (dialog1, ch10_ref_combo, "ch10_ref_combo");
  GLADE_HOOKUP_OBJECT (dialog1, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (dialog1, ch11_chk, "ch11_chk");
  GLADE_HOOKUP_OBJECT (dialog1, label29, "label29");
  GLADE_HOOKUP_OBJECT (dialog1, ch11_hp_entry, "ch11_hp_entry");
  GLADE_HOOKUP_OBJECT (dialog1, label30, "label30");
  GLADE_HOOKUP_OBJECT (dialog1, ch11_tp_entry, "ch11_tp_entry");
  GLADE_HOOKUP_OBJECT (dialog1, label51, "label51");
  GLADE_HOOKUP_OBJECT (dialog1, ch11_rng_combo, "ch11_rng_combo");
  GLADE_HOOKUP_OBJECT (dialog1, label73, "label73");
  GLADE_HOOKUP_OBJECT (dialog1, ch11_ref_combo, "ch11_ref_combo");
  GLADE_HOOKUP_OBJECT (dialog1, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (dialog1, ch12_chk, "ch12_chk");
  GLADE_HOOKUP_OBJECT (dialog1, label31, "label31");
  GLADE_HOOKUP_OBJECT (dialog1, ch12_hp_entry, "ch12_hp_entry");
  GLADE_HOOKUP_OBJECT (dialog1, label32, "label32");
  GLADE_HOOKUP_OBJECT (dialog1, ch12_tp_entry, "ch12_tp_entry");
  GLADE_HOOKUP_OBJECT (dialog1, label52, "label52");
  GLADE_HOOKUP_OBJECT (dialog1, ch12_rng_combo, "ch12_rng_combo");
  GLADE_HOOKUP_OBJECT (dialog1, label74, "label74");
  GLADE_HOOKUP_OBJECT (dialog1, ch12_ref_combo, "ch12_ref_combo");
  GLADE_HOOKUP_OBJECT (dialog1, label14, "label14");
  GLADE_HOOKUP_OBJECT (dialog1, vbox5, "vbox5");
  GLADE_HOOKUP_OBJECT (dialog1, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (dialog1, ch13_chk, "ch13_chk");
  GLADE_HOOKUP_OBJECT (dialog1, label33, "label33");
  GLADE_HOOKUP_OBJECT (dialog1, ch13_hp_entry, "ch13_hp_entry");
  GLADE_HOOKUP_OBJECT (dialog1, label34, "label34");
  GLADE_HOOKUP_OBJECT (dialog1, ch13_tp_entry, "ch13_tp_entry");
  GLADE_HOOKUP_OBJECT (dialog1, label53, "label53");
  GLADE_HOOKUP_OBJECT (dialog1, ch13_rng_combo, "ch13_rng_combo");
  GLADE_HOOKUP_OBJECT (dialog1, label59, "label59");
  GLADE_HOOKUP_OBJECT (dialog1, ch13_ref_combo, "ch13_ref_combo");
  GLADE_HOOKUP_OBJECT (dialog1, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (dialog1, ch14_chk, "ch14_chk");
  GLADE_HOOKUP_OBJECT (dialog1, label35, "label35");
  GLADE_HOOKUP_OBJECT (dialog1, ch14_hp_entry, "ch14_hp_entry");
  GLADE_HOOKUP_OBJECT (dialog1, label36, "label36");
  GLADE_HOOKUP_OBJECT (dialog1, ch14_tp_entry, "ch14_tp_entry");
  GLADE_HOOKUP_OBJECT (dialog1, label54, "label54");
  GLADE_HOOKUP_OBJECT (dialog1, ch14_rng_combo, "ch14_rng_combo");
  GLADE_HOOKUP_OBJECT (dialog1, label60, "label60");
  GLADE_HOOKUP_OBJECT (dialog1, ch14_ref_combo, "ch14_ref_combo");
  GLADE_HOOKUP_OBJECT (dialog1, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (dialog1, ch15_chk, "ch15_chk");
  GLADE_HOOKUP_OBJECT (dialog1, label37, "label37");
  GLADE_HOOKUP_OBJECT (dialog1, ch15_hp_entry, "ch15_hp_entry");
  GLADE_HOOKUP_OBJECT (dialog1, label38, "label38");
  GLADE_HOOKUP_OBJECT (dialog1, ch15_tp_entry, "ch15_tp_entry");
  GLADE_HOOKUP_OBJECT (dialog1, label55, "label55");
  GLADE_HOOKUP_OBJECT (dialog1, ch15_rng_combo, "ch15_rng_combo");
  GLADE_HOOKUP_OBJECT (dialog1, label61, "label61");
  GLADE_HOOKUP_OBJECT (dialog1, ch15_ref_combo, "ch15_ref_combo");
  GLADE_HOOKUP_OBJECT (dialog1, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (dialog1, ch16_chk, "ch16_chk");
  GLADE_HOOKUP_OBJECT (dialog1, label39, "label39");
  GLADE_HOOKUP_OBJECT (dialog1, ch16_hp_entry, "ch16_hp_entry");
  GLADE_HOOKUP_OBJECT (dialog1, label40, "label40");
  GLADE_HOOKUP_OBJECT (dialog1, ch16_tp_entry, "ch16_tp_entry");
  GLADE_HOOKUP_OBJECT (dialog1, label56, "label56");
  GLADE_HOOKUP_OBJECT (dialog1, ch16_rng_combo, "ch16_rng_combo");
  GLADE_HOOKUP_OBJECT (dialog1, label62, "label62");
  GLADE_HOOKUP_OBJECT (dialog1, ch16_ref_combo, "ch16_ref_combo");
  GLADE_HOOKUP_OBJECT (dialog1, label15, "label15");
  GLADE_HOOKUP_OBJECT (dialog1, vbox6, "vbox6");
  GLADE_HOOKUP_OBJECT (dialog1, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (dialog1, label57, "label57");
  GLADE_HOOKUP_OBJECT (dialog1, srate_combo, "srate_combo");
  GLADE_HOOKUP_OBJECT (dialog1, label16, "label16");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog1, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (dialog1, okbutton1, "okbutton1");

  return dialog1;
}

